<h2>1918-01-08 12:00 PM</h2><h1>The Fourteen Points</h1>
	
<p>On January 8, 1918, President Woodrow Wilson gave a speech to Congress in which he presented his Fourteen Points that outlined his program of peace to end World War I. The first five points called for an end to secret treaties, freedom of the seas, free trade, reduction of arms, and adjustment of colonial claims, taking into account the wishes of the colonial population. Wilson's sixth point called for Germany to withdraw from Russian territory and for Russian self-determination of its own government. The President then called for the restoration of Belgian, Italian, and French borders, the establishment of a Polish state, and autonomy for the ethnic peoples of the Austro-Hungarian and Ottoman empires. Wilson's final and, in his mind, most important point was the establishment of a "general association of nations" that would foster international cooperation, freedom, and peace.</p>

<p>Wilson had drafted the Fourteen Points as a series of war aims he hoped would reinvigorate the Allied cause after Russia withdrew from the war following the November 1917 Bolshevik Revolution. The war aims were based on the principle of "peace without victory" that Wilson had proposed in 1916 as a solution to the European stalemate. Along with his adviser, Colonel Edward House, Wilson had come up with his Fourteen Points after more than a year of discussions with other progressive thinkers, especially journalist Walter Lippmann, on what the United States should hope to accomplish through its intervention in the war.</p>

<p>Wilson intended his speech to rally support in the Allied governments to the idea of a league of nations and a more transparent international system. He hoped these war aims would entice the Russian people back into the war by giving them something worthy for which to fight. Wilson also hoped the democratic ideas of the proposal, especially self-determination, would breed unrest in Germany and Austria-Hungary.</p>

<p>The Fourteen Points speech, as the New York <i>Herald</i> dubbed it, became the basis for Allied armistice plans. As Germany neared military defeat in the fall of 1918, the German government approached Wilson first in response to his Fourteen Points plan. The plan's territorial provisions and call for the establishment of a league of nations became the basis for a portion of the Treaty of Versailles, which ended the war in 1919. However, Wilson was unable to convince Britain, France, and Italy to pursue "peace without victory," and he was forced to compromise on many points.</p>

<p>Still, as a work of international relations policy, Wilson's Fourteen Points represent one of the most remarkable efforts of an American President. Wilson's embrace of anti-imperialism and national self-determination made a lasting impact in international relations through the rest of the 20th century. </p>

<p>For more information, please visit the <a href="../wilson">Woodrow Wilson home page</a>.</p><h4>Woodrow Wilson</h4>