
<p>/images/academic/americanpresident/essayimages/01_05.jpg</p>
<h2>1949-01-05 12:00 PM</h2>
<h1>Truman Announces Fair Deal Program</h1>
	
<p>On January 5, 1949, just weeks before the start of his second term as President, Harry S. Truman delivered his State of the Union Address. The speech contained a series of measures that Truman recommended for congressional action. Truman closed his address by citing the philosophy behind this domestic program. “Every segment of our population and every individual,” he explained, “has a right to expect from our government a fair deal.” His list of demands thus became known as the “Fair Deal,” an attempt by Truman to augment Roosevelt's New Deal. Nevertheless, where Roosevelt had met with great success in implementing his proposals, Truman struggled to pass his program. Of all the goals he presented, only three-increasing public housing programs, raising the minimum wage, and expanding Social Security-were fulfilled by the end of the congressional session in 1950.</p>
<p>Truman's Fair Deal included a wide ranging group of proposals: economic controls to halt inflation, a more progressive tax structure, the raising of the minimum wage, repeal of the Taft-Hartley Act, agricultural reform, resource development and public power, national medical insurance, expansion of Social Security, federal housing programs, aid to education, and  civil rights protections. The President, however, faced numerous difficulties in passing his liberal legislative program. Despite the election of Democratic majorities to both the House and the Senate, a coalition of Republicans and conservative Democrats from the South continued to dominate both chambers of Congress. For example, Truman proposed cloture reform-reducing the number of votes necessary to end a filibuster in the Senate-to facilitate the passage of civil rights legislation. Conservative Senators narrowly defeated this proposal, shutting down the possibility of more liberal legislation. Other aspects of Truman's program met with opposition from powerful interest groups. The administration's agricultural reform bill was defeated through the influence of the Farm Bureau Federation; likewise, the American Medical Association lobbied against national healthcare. These forces limited Congress's ability to pass substantial parts of the Fair Deal.</p>
<p>Those programs that were enacted barely made it through Congress. Even with the support of conservative Senator Robert Taft, the Housing Act of 1949 passed an important vote in the House by a margin of only five representatives; the act was weakened version of the public housing bill the President proposed, but it still promised to build 810,000 housing units over the next six years. Congress also raised the minimum wage in 1949 from 40 to 75 cents. Finally, the Social Security Act of 1950 expanded significantly the coverage offered in the original 1935 act. While Truman failed to implement most of his Fair Deal, the passage of these three acts and other smaller pieces of legislation were significant victories for the President and liberals in Congress.</p>

<h4>Harry S. Truman</h4>