
<h2>1863-01-01 12:00 PM</h2><h1>Emancipation Proclamation Issued</h1>

<p>On January 1, 1863, President Abraham Lincoln issued the Emancipation Proclamation. With it, he freed all slaves in Confederate or contested areas of the South. However, the Proclamation did not include slaves in non-Confederate border states and in parts of the Confederacy under Union control.</p>
<p>During the war, Republicans and Northern free blacks called on the President to act decisively to end slavery. Members of the Lincoln administration also hoped that an act of emancipation would make it difficult for Britain or France to officially recognize the Confederacy in view of the antislavery sentiments among their home populations–especially in Britain. In July 1862, President Lincoln announced to his cabinet that he intended to issue an Emancipation Proclamation in his capacity as Commander in Chief of the armed forces in the time of war. The Proclamation would free all slaves in areas still in rebellion, and henceforth it would be a Union objective to destroy slavery within the Confederate South. His cabinet persuaded Lincoln to wait until a Union victory, lest it appear to the world like an act of desperation. </p>
<p>After General George McClellan stopped Robert E. Lee's advance into Maryland at Antietam Creek in September 1862, Lincoln announced his preliminary Proclamation. The President warned that if the rebellion did not end by January 1, 1863, he would issue his presidential order of emancipation and move to destroy slavery in the rebel states once and for all. In the Proclamation, Lincoln left out occupied Tennessee and certain occupied parts of Louisiana and Virginia as well as the loyal slave states. The document declared, with the exception of those areas, that all slaves in the rebellious states were hereafter "forever free." It also asserted that the Union Army would now receive black men into the service as regular soldiers. (The U.S. Navy had accepted black sailors from the beginning of the war.)</p>
<p>In a single stroke of his pen, Abraham Lincoln issued the most revolutionary measure ever to come from an American President up to that time. Still, the President was worried that the courts might void his wartime Proclamation after the war on the grounds that any confiscation of "property" required due process of law, and that such a policy could only be adopted by a law passed by Congress. Thus, Lincoln used his reelection victory in 1864 to promote a constitutional amendment that would end slavery everywhere in the nation. The Republican platform of 1864 endorsed the Thirteenth Amendment–which the U.S. Senate had passed in April. Lincoln used all the powers of his office, including patronage, to push it through the House, which adopted the amendment on January 31, 1865. The Thirteenth Amendment was ratified in December 1865.</p>

<p>To read the full text of the Emancipation Proclamation, click <a href="http://millercenter.org/scripps/archive/speeches/detail/3509">here</a>.</p>
<p>For more information, please visit the <a href="../lincoln">Abraham Lincoln home page</a>.</p><h4>Abraham Lincoln</h4>
