
<p>/images/academic/americanpresident/essayimages/01_17.jpg</p>
<h2>1991-01-17 12:00 PM</h2>
<h1>Persian Gulf War Begins</h1>

<p>Early on the morning of January 17, 1991, coalition forces led by the United States launched air strikes against Iraq. These strikes signaled the beginning of the military phase of the Persian Gulf War.</p>
<p>In August 1990, Iraq invaded Kuwait, a neighboring country. Iraq's leader, Saddam Hussein, had long argued with Kuwait over the rights to certain oil-rich lands. He had been preparing to invade Kuwait for several weeks, but when the attack came-on August 2, 1990-it nevertheless surprised much of the world. Several countries in the Middle East had assured the United States that Hussein was massing his troops only to bluff Kuwait into meeting his demands. When the Iraqi leader sent 140,000 troops storming toward-and quickly taking-the Kuwaiti capital, President George H.W. Bush responded.</p>
<p>The United States quickly intervened for a number of reasons. By invading Kuwait, Saddam Hussein gained control over a vast amount of the world's oil supply, which gave him the potential to wreak havoc with U.S. energy policy and oil prices. Bush also drew vivid parallels between Saddam Hussein and Adolf Hitler in the 1930s: a decisive, early blow to Saddam's imperialist ambitions, the President believed, would forestall another “Munich,” preventing the outbreak of a more serious crisis later on. Finally, political and military theorists thought that a show of U.S. military resolve would improve America's international credibility-especially in this first major crisis of the post-Cold War era-and boost confidence in a military still trying to throw off the legacy of the Vietnam War.</p>
<p>President Bush and his administrative team were extraordinarily active, and extraordinarily successful, in building an international coalition to counter the Iraqi aggression. Perhaps the most impressive feat of international diplomacy was President Bush's ability either to neutralize or win outright the support of traditionally hostile China and Russia, together with many countries of the Middle East. He also persuaded Israel to stay out of the coalition, which made it possible for Middle Eastern countries to join without seeming to unite with Israel.</p>
<p>The United Nations first approved the use of sanctions and a U.S.-led defensive posture, designed to deter Saddam Hussein from advancing any further and to persuade him to pull back from Kuwait. In November, the U.N. Security Council passed Resolution 678 authorizing member states to use “all necessary means” to remove Iraq from Kuwait if Iraq had not withdraw all of its forces by January 15, 1991. The U.S. plan to forcibly remove Iraqi troops from Kuwait was dubbed Operation Desert Storm and included an effective mixture of air power and overwhelming ground forces, including the use of 500,000 U.S. troops. Once the deadline passed and Iraq had not withdrawn from Kuwait, the U.S.-led coalition quickly overpowered the Iraqi military, and on February 28th, the coalition declared a cease-fire.</p>
<p>When the war ended, President Bush had very high approval ratings for his conduct of the war and his success in coalition building. However, he endured criticism for failing to remove Saddam Hussein from power and destroy the Iraqi military. That stance left Kurds and Shiites who were sympathetic to the United States at the mercy of a vengeful Iraqi government, but President Bush apparently feared the consequences of Saddam Hussein's unknown replacement-and a geopolitically destabilized region-even more than Saddam himself. </p>

<h4>George Herbert Walker Bush</h4>