
<p>/images/academic/americanpresident/essayimages/01_20.jpg</p>
<h2>2009-01-20 12:00 PM</h2>
<h1>Barack Obama Inaugurated</h1>

<p>On January 20, 2009, Barack Obama was inaugurated as the 44th President of the United States. He was the first African American President in U.S. history. </p>
<p>Obama emerged as an unlikely candidate during the 2008 presidential campaign. He was born and raised in Hawaii. His mother, a white American from Kansas, and his father, a black Kenyan studying in the United States, met as students at the University of Hawaii. After attending school in Hawaii, Obama moved to the mainland for college&mdash;first attending Occidental College in Los Angeles, California, and then graduating from Columbia University in New York City.</p> 
<p>Obama then moved to Chicago, Illinois, and began working as a community organizer, helping low-income residents improve their public housing conditions. In 1988, he enrolled at Harvard Law School. During the 1990-1991 academic year, he was president of the prestigious Harvard Law Review, the first African American elected to the position. Returning to Chicago, Obama worked in a civil rights law firm and as a lecturer at the University of Chicago. </p>
<p>He first entered public office as a state senator in 1997. Obama attracted national attention in the summer of 2004 when he gave the keynote speech at the Democratic National Convention. “There's not a liberal America and a conservative America,” he declared. “There's a United States of America. There's not a black America and white America and Latino America and Asian America. There's a United States of America.”</p>
<p>After serving as a state legislator for eight years, Obama ran for the U.S. Senate and won the election in 2004 by the largest margin in the history of Senate elections in Illinois. As a first-term Senator, he launched his presidential campaign in February 2007. After a hard-fought Democratic primary against Senator and former First Lady Hillary Clinton, Obama secured the Democratic Party nomination in June 2008. Two days before the Democratic National Convention, he picked Senator Joseph Biden of Delaware as his vice presidential running mate.</p>
<p>The 2008 presidential campaign featured the Democratic ticket of Barack Obama and Joseph Biden against the Republican ticket of Senator John McCain of Arizona and his vice presidential running mate, Governor Sarah Palin of Alaska. Obama and Biden won the election handily, 53 percent of the popular vote to 46 percent and 365 Electoral College votes to 173. </p>

<h4>Barack Obama</h4>