
<p>/images/academic/americanpresident/essayimages/01_30.jpg</p>
<h2>1968-01-30 12:00 PM</h2>
<h1>Tet Offensive Begins</h1>

<p>On January 30, 1968, on the Vietnamese Lunar New Year of Tet, the North Vietnamese Army and the National Front for the Liberation of South Vietnam coordinated a massive offensive against South Vietnam. More than 80,000 troops and guerrillas attacked 44 provincial capitals, 64 district capitals, and 5 of South Vietnam's major cities. While the South Vietnamese and United States troops reversed most of the offensive's gains in the following two weeks, some intense fighting continued for months after the attack. In the end, the Tet Offensive failed to deliver a military victory for the North Vietnamese, but it did create a crisis for the administration of President Lyndon B. Johnson.</p>
<p>For ten days before the attack, the U.S. military had focused its attention on relieving the siege of a marine outpost at Khe Sanh close to the demilitarized zone. American officers feared that this siege would turn into another Diem Bien Phu, the final siege before the French abandoned Vietnam in 1954. To protect Khe Sanh, U.S. military commanders moved troops away from populated areas on the coast. This move left cities and capitals vulnerable to the attacks of the offensive. After the Tet Offensive began, the North Vietnamese halted their siege of Khe Sanh, but managed to take other targets in the region like the ancient imperial capital of Hue. It took American and South Vietnamese troops almost a month to recapture Hue. Still, the United States managed to turn the Tet Offensive into a military victory. While loses were high on both sides, the actions of the American military saved the South Vietnamese regime from collapse.</p>
<p>Back in the United States, however, the American public had a very negative reaction. President Johnson, his administration, and U.S. generals had been telling the American people for months that the situation in Vietnam was under control. After the offensive, they quickly lost their credibility. Prominent journalists, such as Walter Cronkite, began to doubt that the United States could win the war and voiced these fears in newspapers and on television. On February 3, days after the attack, millions of Americans watched on their televisions as a Saigon police officer summarily shot a Viet Cong guerilla in the head on a Saigon city street. More than ever before, many Americans began to have doubts about the war. One public opinion survey conducted after Tet found that 78 percent of the American public thought that the United States was not making progress in the war.</p>
<p>The reaction of the American public to the Tet Offensive had serious consequences for the Johnson administration. Militarily, it forced the administration to reconsider its strategy in Vietnam, leading to a partial halt in the bombing of the North. Politically, the Tet Offensive shattered the President's political future. On March 31, two months after the start of the offensive, President Johnson announced that he would not run for reelection. </p>

<h4>Lyndon Baines Johnson</h4>