
<h2>1865-01-31 12:00 PM</h2><h1>House Passes Thirteenth Amendment</h1>

<p>On January 31, 1865, the House of Representatives passed the Thirteenth Amendment, which made slavery illegal in the United States. The Senate had passed the amendment in April 1864. With Congress's approval, the amendment then went to the states for ratification. By December 1865, enough states had ratified the amendment to make it constitutionally binding.</p>  
<p>The Thirteenth Amendment had two sections. Section one read: “Neither slavery, nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction.” Section two stated that Congress had the power to pass legislation to enforce the abolition of slavery.</p>
<p>Prior to becoming President, Abraham Lincoln had compromised on the slavery issue in the political arena. Although Lincoln clearly hated slavery, he assumed the presidency promising not to interfere with it. During the American Civil War, President Lincoln noted again and again that his purpose in fighting the South was to save the Union, not to free the slaves. But as the war dragged on and more and more slaves from the South fled to the Union Army, Lincoln began to reconsider slavery, and he came under more and more pressure to free the slaves.</p> 
<p>In July 1862, the President announced to his cabinet that he would issue the Emancipation Proclamation in his capacity as commander in chief of the armed forces in time of war. The Proclamation would free all slaves in areas still in rebellion, and henceforth it would be a Union objective to destroy slavery within the Confederate South. After the Union Army defeated the Confederates at the Battle of Antietam in September 1862, Lincoln announced the Emancipation Proclamation and warned that if the war did not end by January 1, 1863, the Emancipation would go into effect and the Union would move to destroy slavery in the rebel states forever.</p> 
<p>During his reelection campaign of 1864, President Lincoln promoted a constitutional amendment that would end slavery throughout the country. Lincoln used all the powers of his office to have Congress pass the amendment. Lincoln, however, did not live to see the Thirteenth Amendment become part of the Constitution. The President was assassinated in April 1865, and the amendment was ratified in December of that year.</p> 

<p>For more information, please visit the <a href=""../lincoln"">Abraham Lincoln home page</a>.</p><h4>Abraham Lincoln</h4>