
<h2>1898-02-15 12:00 PM</h2><h1>Battleship <em>Maine</em> Sinks</h1>

<p>On the night of February 15, 1898, a fire in a coal bunker of the battleship <em>Maine</em> ignited a reserve gunpowder magazine, blowing the ship in half and killing 266 crew members. "Remember the <em>Maine</em>!" became a rallying cry for Americans who wanted to go to war against Spain over the island of Cuba. President William McKinley tried to find a diplomatic solution to resolve the conflict but ultimately Spain declared war against the United States, beginning the Spanish-American War.</p>
<p>Spain had long controlled the Caribbean island of Cuba but throughout the 19th century, the Cuban people had struggled to gain independence. In 1895, Cuban rebels led a revolt against Spanish rule. When Spain tried to quash the rebellion, the American press publicized conditions in Cuba and atrocities committed by the Spanish. Public opinion in the United States began to clamor for U.S. government involvement.</p>
<p>In January 1898, the United States dispatched the battleship <em>Maine</em> to Cuba both to protect American citizens and property and to demonstrate that the United States still valued Spain's friendship. The <em>Maine</em> arrived in the Havana harbor on January 25, 1898. Over the next few weeks, its officers enjoyed friendly relations with Spanish officials ashore.</p> 
<p>After the explosion and destruction of the battleship, pro-interventionists, including Theodore Roosevelt and the "yellow press," attributed the disaster to Spanish sabotage and beat the drums for war. President McKinley called for calm, urging Americans to wait for the results of a naval investigation of the explosion. Spain immediately sent its entire diplomatic delegation to express the nation's sympathy to McKinley and conducted its own investigation of the disaster. However, public furor over the incident grew.</p>
<p>On March 28, the naval court of inquiry presented its findings to Congress, concluding incorrectly that an external explosion, such as an underwater mine, had destroyed the <em>Maine</em>. (A later naval study concluded that an internal explosion had destroyed the <em>Maine</em>.) The court failed to name the responsible party in their erroneous verdict, but the American public instantly assumed Spanish culpability. </p>
<p>Wary of starting a war, President McKinley urged the Spanish to agree to an armistice with Cuban rebels and demanded an end to civil rights abuses against the Cuban people. When the Spanish government wavered on an armistice behind the pressures of its own public opinion, McKinley asked Congress for the power to take military action against Spain in Cuba on April 11, 1898, thereby hoping to stabilize the region for American interests and quell the humanitarian disaster that war had brought to Cuba. Congress passed a series of four resolutions on April 19 recognizing Cuban independence and gave McKinley the power to eject Spain from the island. McKinley used these powers to declare a blockade of Cuba on April 21, leading the Spanish Empire to declare war on the United States on April 23, 1898. Two days later, the United States declared war against Spain. The Spanish-American War had begun.</p>

<p>For more information, please visit the <a href="../mckinley">William McKinley home page</a>.</p><h4>William McKinley</h4>