<p>/images/academic/americanpresident/essayimages/02_21.jpg</p>
<h2>1972-02-21 12:00 PM</h2>
<h1>President Richard Nixon Arrives in China</h1>

<p>On February 21, 1972, President Richard Nixon arrived in Beijing, China. It was the first time an American President had visited the country.</p>  
<p>Nixon, his wife, Pat, and his entourage, including National Security Adviser Henry Kissinger, visited China from February 21 to February 27. The eight-day visit included official meetings, cultural visits, and sightseeing in Beijing, Hangchow, and Shanghai. The media extensively covered the trip, televising many of the events. Chairman Mao Zedong and Premier Zhou En-Lai met with President Nixon and American officials, and the people of both nations saw the beginning of a diplomatic thaw most thought impossible only months earlier. At his farewell banquet, President Nixon remarked in his toast, “This was the week that changed the world.”</p>
<p>In late 1971, President Nixon had stunned the world by announcing that he would visit “Red China,” the first visit by an American President to the world's most populous country. It was a startling announcement from a politician who had built much of his political career championing anti-Communism and using the issue as a means to ascend through the higher reaches of American government. Nixon had long harbored great antipathy for Communism and its adherents from his work on the House Committee for Un-American Activities in the 1940s to his stands as vice president in the Eisenhower administration to his own pronouncements as President.</p>  
<p>As President, Nixon reasoned that improving relations with China would allow him to inject more fluidity into the international environment and offset the growing power of the Soviet Union. But in order to improve relations with China, he had to resolve the Taiwan issue. Until 1971, Nixon had been a supporter of the pro-Taiwan lobby that had blocked any move to recognize the People's Republic of China.</p> 
<p>At the end of the visit, China and the United States jointly issued the Shanghai Communiqu&eacute;, which pledged that both countries wanted to strive toward normalizing relations. The United States also agreed that there was one China and Taiwan was part of it and that the United States would work toward the ultimate objective of removing U.S. forces from Taiwan. The most lasting contribution of the Nixon visit was a rapprochement with China itself, with the United States recognizing the People's Republic of China as the sole diplomatic voice of China.</p>
<p>European allies applauded the trip, but leaders in Japan and Taiwan viewed the diplomatic move with caution and concern. Nixon's secret diplomacy also concerned many who felt that matters of national interest ought to be debated publicly. Still, Nixon's historic visit to China in 1972 opened the door to relations between two of the world's most powerful countries, China and the United States.</p>

<h4>Richard Nixon</h4>