
<h2>1820-03-06 12:00 PM</h2><h1>Monroe Signs Missouri Compromise</h1>

<p>On March 6, 1820, President James Monroe signed the Missouri Compromise. The Compromise was made up of three parts: it admitted Maine, part of northern Massachusetts, as a free state; it admitted Missouri as a slave state; and it henceforth restricted slavery to territories south of the latitude 36º30' north.</p>
<p>The controversy began in Congress in early 1819 when Missouri applied for admission to the Union. Debates raged between those who wanted to limit slavery in Missouri in exchange for its admission as a state and those who wanted Missouri admitted as a state without preconditions. The volatile issue of slavery, which had been somewhat balanced by an equal split between slave and free states, flared back into public debate. Those who supported slavery believed that states should decide on their own whether to allow slavery. Those who opposed slavery wanted to stop its spread throughout the country. Speaker of the House Henry Clay finally engineered a compromise that balanced the slave state of Missouri with the free state of Maine, and limited the future expansion of slavery into the territories of the United States. </p>
<p>President Monroe did not speak publicly about the crisis or the Compromise, but he worked behind the scenes to secure the result he wanted. He did not think it was constitutional for Congress to impose restrictions on admitting the state of Missouri that it had not imposed on other states, and he threatened to veto any bill that contained such restrictions. Although Monroe did not support limiting slavery, he pragmatically supported the Missouri Compromise because he valued the integrity of the Union and did not want it to come apart. </p>
<p>Monroe privately corresponded with Senator James Barbour of Virginia, encouraging him to promote the Compromise legislation, which Barbour did. Monroe also feared that northern Federalists were promoting restrictions to Missouri's admittance into the Union because they wanted to split the Jefferson Republicans and make their party a legitimate opposition party again. It was this fear of a resurgent Federalist Party that Monroe and Barbour used to quiet the hard-core Jeffersonian Republicans of Virginia, who wanted no limits on slavery whatsoever. Virginia Republicans even threatened to withhold their state's nomination of Monroe for a second term as President if he supported the Compromise. Barbour's lobbying and evocation of the alleged Federalist threat convinced them to support Monroe.</p>
<p>Although President Monroe was not openly involved in the congressional debates, he supported the Compromise and worked quietly for its passage. Monroe's political skills helped solve the Missouri Crisis and preserve his own candidacy in the 1820 presidential election.</p>

<p>For more information, please visit the <a href=""../monroe"">James Monroe home page</a>.</p><h4>James Monroe</h4>
