
<h2>1965-03-15 12:00 PM</h2><h1>Johnson Introduces Voting Rights Act</h1>

<p>On March 15, 1965, President Lyndon Johnson addressed a joint session of Congress to introduce voting rights legislation. In a moving oration, Johnson called on white Americans to make the cause of African Americans their cause too. Together, he explained, echoing the anthem of the civil rights movement, "we shall overcome."</p>
<p>After winning reelection in 1964, President Johnson realized the need for significant voting rights legislation, but, as he explained to Martin Luther King, Jr., he felt that such a bill would hold up the passage of other programs in his domestic program. Still King and other civil rights leaders sought ways to bring the issue of voting rights to the attention of the American people.</p>
<p>Selma, Alabama, provided the perfect opportunity for civil rights organization such as the Southern Christian Leadership Conference (SCLC) and the Student Nonviolent Coordinating Committee (SNCC) to stage a nonviolent campaign on the issue of voting rights. The city of Selma had 15,000 African Americans of voting age but only 355 were registered to vote. Furthermore, the city's board of registers used blatantly racist tactics to keep African Americans off the voting rolls. SNCC and SCLC leaders decided to lead a march from Selma to Montgomery, the capital of Alabama, to protest the gross disenfranchisement of African Americans.</p>   
<p>On March 7, 1965, more than 500 marchers attempted to cross the Edmund Pettis Bridge, when state troopers confronted them and demanded that they turn around. The marchers halted facing the troopers, and the troopers advanced on the marchers, attacking them with nightsticks and tear gas. SNCC leader John Lewis was clubbed in the head and suffered a skull fracture. Images of the attacks on the peaceful marchers were broadcast throughout the country, and the incident became known as "Bloody Sunday." Two days later, Martin Luther King, Jr., led a group of protestors on another march from Selma. When police confronted them, however, they knelt in prayer and turned around.</p>  
<p>In his address to Congress on March 15, President Johnson used stirring oratory to create support for voting rights legislation. He spoke of events in Selma as a historic moment and continually pressed the right to vote as a fundamental American right, proclaiming, "Every American citizen must have an equal right to vote." He stressed that denying the right to vote to African Americans cheapened the ideals of America for everyone. (<a href="../../../scripps/digitalarchive/speeches/spe_1965_0315_johnson">Click here</a> to read and listen to his speech in its entirety.)</p> 
<p>The Voting Rights Act passed both houses of Congress with bipartisan support. On August 6, 1965, President Johnson signed the Voting Rights Act. The act outlawed practices, such as literacy tests, that had been used to keep African Americans from registering to vote. The Justice Department gained the power to intervene where discriminatory practices had kept less than 50 percent of eligible voters from registering to vote. If this intervention failed to fix the situation, federal registers could take over the local voting systems.</p>
<p>President Johnson, the master legislator, pushed for the passage of a strong bill to end the disenfranchisement of African Americans in the South. Together with the Civil Rights Act of 1964, the Voting Rights Act effectively ended the systematic segregation of the South.</p>

<p>To read and listen to the full text of Johnson's speech, click <a href="http://millercenter.org/scripps/archive/speeches/detail/3386">here</a>.</p>
<p>For more information, please visit the <a href="../lbjohnson">Lyndon Baines Johnson home page</a>.</p><h4>Lyndon Baines Johnson</h4>
