
<p>/images/academic/americanpresident/essayimages/03_30.jpg</p>
<h2>1981-03-30 12:00 PM</h2>
<h1>President Reagan Shot</h1>

<p>On March 30, 1981, President Ronald Reagan was shot by John W. Hinkley, Jr., while leaving the Washington Hilton Hotel after giving a speech. The President was hit under his left arm by a bullet that ricocheted off his limousine. Once the sound of shots rang in the air, Secret Service agent Jerry Parr shoved Reagan into his limousine, and then, after noticing the President had been shot, directed the car to the George Washington University Hospital.  Press Secretary James Brady, Secret Service Agent Timothy McCarthy, and Washington, D.C., police officer Thomas Delahanty were also shot and seriously wounded.</p>
<p>Parr's quick-witted diversion of the presidential limousine to the hospital was a move that probably saved Reagan's life. The bullet had missed Reagan's heart by a mere inch. Although not believed to be serious at the time, Reagan's wounds were in fact life-threatening. He underwent surgery to remove the bullet and repair a lung that had collapsed.</p>
<p>Still President Reagan, ever the trouper, walked into the hospital before he collapsed. Later he won the heart of the nation when the stories of his courage and humor disarmed critics and endeared him to the public. When he arrived at the hospital, he reportedly joked with the medical staff, “Please tell me you're Republicans,” and he quipped to an anxious Nancy, “Honey, I forgot to duck.” One of the older Presidents when elected, Reagan was 70 years old when he took the oath of office; questions about his stamina and energy were commonplace during the early months of his presidency. His quick recovery from the assassination attempt, however, helped to brush those concerns aside.</p>
<p>President Reagan appeared before a joint session of Congress a few months after the assassination attempt to thunderous support. The attempt on his life and speedy recovery from his wounds helped establish his reputation for toughness, humility, and strength-a far cry from the public perception of his predecessor, Jimmy Carter. Press Secretary James Brady, however, suffered permanent brain damage from his wounds, and later advocated the passage of gun control laws. The “Brady Bill,” named in his honor, limited handgun purchases and required background checks on gun purchasers.</p>
<p>In 1982, a District of Columbia jury tried John W. Hinkley, Jr., and found him not guilty by reason of insanity. He was then committed to St. Elizabeth's Hospital for treatment of his mental illness.</p>

<h4>Ronald Wilson Reagan</h4>
