
<h2>1968-03-31 12:00 PM</h2><h1>Johnson Announces Decision Not to Seek Reelection</h1>

<p>On March 31, 1968, President Lyndon Johnson, during a prime-time televised address, announced that he would not seek reelection. “There is division in the American house now. There is divisiveness among us all tonight.” Johnson explained. “And holding the trust that is mine, as President of all the people, I cannot disregard the peril to the progress of the American people and the hope and prospect of peace for all people. . . . I do not believe that I should devote an hour or a day of my time to any personal partisan causes. . . . Accordingly, I shall not seek, and I will not accept, the nomination of my party for another term as your President.” The Vietnam War had shattered Johnson's political future.</p> 
<p>The domestic reaction to the Tet offensive launched by the North Vietnamese in January 1968 created great strain on his presidency. In March, when former Truman advisor Clark Clifford became Johnson's new Secretary of Defense, the President requested a reevaluation of the war. The generals were calling for an additional 206,000 American troops to join the half a million soldiers already in Vietnam. Clifford thought such a move would be both politically and economically disastrous. The cost of any further escalation would threaten America's economic standing in the world and could detract from then nation's ability to maintain its strategic commitments in Europe. Clifford advised Johnson against large scale escalation, requesting that he send only about 20,000 additional soldiers.</p>
<p>Meanwhile, displeasure with Johnson's war policy became part of the 1968 presidential race. On March 12, Senator Eugene McCarthy of Minnesota, running on a platform opposed to continuing the war, won 41 percent of the vote in the New Hampshire Democratic Primary. While Johnson won the primary, McCarthy's strong showing against a sitting President demonstrated the displeasure with the Johnson administration. On March 16, Robert F. Kennedy, Johnson's long-time political rival, announced that he too would challenge the President for the Democratic nomination. While Johnson was still the most likely Democratic nominee, this intraparty competition threatened to shatter the party.</p>
<p>In late March, Secretary Clifford assembled some of the top foreign-policy experts to discuss the future of the war in Vietnam. Known as the “wise men,” the group included Dean Acheson, Maxwell Taylor, George Ball, McGeorge Bundy, Matthew Ridgeway, and Henry Cabot Lodge. Some of the wise men supported the idea of increased escalation in the war. Most, however, concluded that Vietnam was, in Bundy's words, “a bottomless pit.” Additional U.S. troops would not quickly lead to an end of the war, only an increase in American casualties. Following their advice, Johnson chose to call for a partial halt in the bombing of North Vietnam and agreed to consider peace talks with the North Vietnamese.</p>
<p>In his announcement on March 31, President Johnson also told the American people about the partial bombing halt in North Vietnam. He stated that there would be no bombing of North Vietnam except in the area near the demilitarized zone and asked Ho Chi Minh to respond positively to this gesture. Johnson finished his announcement on Vietnam; then he paused dramatically before launching into his decision not to run for reelection.</p> 

<p>To read President Johnson's entire address, click <a href=""http://millercenter.org/scripps/archive/speeches/detail/3388"">here</a>.</p>
<p>For more information, please visit the <a href=""../lbjohnson"">Lyndon Baines Johnson home page</a>.</p><h4>Lyndon Baines Johnson</h4>
