
<p>/images/academic/americanpresident/essayimages/04_04.jpg</p>
<h2>1841-04-04 12:00 PM</h2>
<h1>President Harrison Dies</h1>

<p>On April 4, 1841, President William Henry Harrison died of pneumonia, exactly one month after his inauguration as the ninth President of the United States. The sixty-eight-year-old President likely had caught a cold while standing outside in harsh weather with no hat or coat during his nearly two-hour inaugural speech. Harrison's health further deteriorated under the constant barrage of office seekers who sought his favor from the moment he assumed office. Only three weeks after his inauguration, Harrison was bedridden, his cold having developed into pneumonia. He whispered his last words to the attending doctor, although they may have been intended for Vice President John Tyler: “Sir, I wish you to understand the true principles of the government. I wish them carried out. I ask nothing more.”</p>
<p>Harrison's administration was the shortest in American history, and his death marked the first of a sitting President. Harrison's death also opened the sticky and untested issue of presidential succession. The Constitution stated that upon the death of a President the “Duties of said office” were to “devolve on the Vice President,” and the 12th Amendment provided for the Vice President to “act as President” when there was no Executive. But neither document stated explicitly whether the vice president was now himself President, or merely taking on the responsibilities of the office until a new election could be held.</p>
<p>Harrison's cabinet dispatched a messenger to inform Vice President Tyler of Harrison's death, summoning him to the nation's capital. Upon his arrival two days later in Washington, D.C., Tyler immediately met with Harrison's cabinet to discuss the matter of succession. Quickly the cabinet members agreed that Tyler should take the oath of office and become President in his own right. Tyler's assumption of the vacated office in the wake of Harrison's sudden death established the procedure and precedent for presidential succession - and averted a possible constitutional and political problem.</p>

<h4>William Henry Harrison</h4>
