
<h2>1917-04-06 12:00 PM</h2><h1>United States Declares War on Germany</h1>

<p>On April 6, 1917, the United States declared war on Germany. Although President Woodrow Wilson had campaigned for reelection in 1916 emphasizing how he had kept the United States out of the war, he soon realized that the United States could not stand by and remain neutral in the Great War.</p> 
<p>At the end of January 1917, German U-Boats resumed unrestricted submarine warfare, attacking ships in the Atlantic Ocean. Shortly afterwards, the British released the Zimmermann telegram to the American government. The telegram revealed a German plot to try to entice Mexico into joining against the United States. President Wilson told the nation at his second inaugural on March 5 that he felt the United States had no control over its neutral status and that outside pressures “have drawn us more and more irresistibly into their current and influence.”</p>
<p>Nevertheless, Wilson remained locked in a remarkable struggle between conflicting principles in his own ideology over the decision whether to go to war. Congress and the public were divided enough on the issue of intervention that the decision to enter the Great War fell on Wilson alone. He remained hopeful in early 1917 for a “peace without victory” that would secure a balance of power and equality of rights for all sides. But he feared that war would undo the progressive reforms he sought domestically and exacerbate the social divisions already present in the country. Nevertheless, Wilson believed that German behavior stood out of bounds of the civilized world and that a German victory would have disastrous consequences for Western civilization.</p> 
<p>After the American press published the Zimmermann telegram, Wilson could count on support for a declaration of war if he asked for one from Congress. On April 2, 1917, the President decided to address a joint session of Congress that night. Wilson's speech asked for a declaration of war not as a crusade for justice, but as a somber and terrible act to “make the world safe for democracy.” In the speech, the President asked for increased taxation, a compulsory draft, and government repression of dissent to support the war cause. The Senate debated a war declaration first, passing it on April 4, and the House passed it on April 6. American troops did not enter combat until more than a year later.</p>

<p>To read the full proclamation from April 6, 1917, declaring a state of war between the United States and Germany, click <a href=""http://millercenter.org/scripps/archive/speeches/detail/3798"">here</a>.</p>

<p>For more information, please visit the <a href=""../wilson"">Woodrow Wilson home page</a>.</p><h4>Woodrow Wilson</h4>
