
<h2>1952-04-08 12:00 PM</h2><h1>Truman Seizes Control of Steel Industry</h1>

<p>On April 8, 1952, President Harry Truman seized control of steel industry, allowing the federal government to administer and oversee the industry. The seizure resulted after the steel producers and steel workers had been unable to reach agreement on a new contract. Truman justified this action under his authority as President but it resulted in a stunning rebuke for him.</p>
<p>On December 31, 1951, the contract between the nation's steel producers and the United Steelworkers Union expired. Weeks of negotiations had failed to produce an acceptable agreement. Since Truman had created a new bureaucracy to manage the economy during the Korean War, both the union and management looked to these agencies to provide a solution. Truman referred the dispute to Wage Stabilization Board (WSB) and requested that both sides continue production until the board made a decision. In March 1952, the WSB voted to give labor a raise of 26 cents an hour. To pay for this increase in wages, the steel manufacturers appealed to the Office of Price Stabilization (OPS) to raise the price of steel but the OPS rejected the request. The administration again attempted to negotiate a compromise, but the steel companies refused to accept the price increases offered by the government, and the union would only accept the raise promised by the WSB. With negotiations at an impasse, a strike appeared inevitable.</p><p>Throughout the ordeal, Truman's objectives were to avert a strike, maintain steel production, and stay on good terms with labor, an important Democratic constituency.  Viewing steel as necessary to the war effort,  he could not allow a strike to begin. Yet, he refrained from using his powers to force the union back to work under the Taft-Hartley Act. He believed that to do so would be to punish labor for management's intransigence and strengthen the political position of the Republican Party. So instead he issued Executive Order 10340 to have the secretary of commerce seize control of the steel industry.</p>
<p>Both the courts and public opinion opposed Truman's action. According to a Gallup poll, 43 percent of Americans disapproved of the seizures. In April, a federal district court found Truman's actions unconstitutional. Two months later, the U.S. Supreme Court upheld the lower court's finding in a 6 to 3 decision.</p> 
<p>With control of the steel plants back in private hands, a fifty-three day strike ensued. In July, the President was finally able to get both sides to agree to terms similar to those on the table at the start of the year. Truman had risked much of his political capital on a strike that, in the end, had minimal effect on the Korean War. The choices he made in this incident increased the unpopularity of an already embattled President.</p>

<p>For more information, please visit the <a href="../truman">Harry S. Truman home page</a>.</p><h4>Harry S. Truman</h4>
