
<h2>1865-04-15 12:00 PM</h2><h1>President Abraham Lincoln Dies</h1>

<p>On April 15, 1865, President Abraham Lincoln died. He had been shot by an assassin the night before and died of a head wound early on the morning of the 15th.</p>
<p>President Lincoln had been sworn in to his second term of office on March 4, 1865. On April 9, he oversaw the end of the American Civil War when the Confederate Army surrendered to the Union. It had been a remarkable spring for the commander in chief.</p>
<p>On April 14, Lincoln sat in Ford's Theater in Washington, D.C., watching a play when a man burst into the presidential box and shot the President in the back of his head. The assassin, John Wilkes Booth, leaped from the box to the stage to make his escape, shouting "Sic semper Tyrannis! (Thus always to Tyrants) The South is avenged!"</p>
<p>The President died at 7:22 a.m. the next morning in the home of William Petersen. A few hours after Lincoln's death, Chief Justice Salmon P. Chase swore Vice President Andrew Johnson in as President of the United States.</p>
<p>The assassin, Booth, was an actor and an ardent Confederate sympathizer who had planned to kill Lincoln along with accomplices who were supposed to kill Secretary of State William H. Seward, Vice President Andrew Johnson, and General Ulysses S. Grant. However, the plan went array, and only Booth carried out his part of the plan. Four of his co-conspirators were convicted and hanged for taking part in the plot or for having known about it in advance. Booth was discovered in a barn in rural Virginia ten days after Lincoln's assassination after frantic searching by the Army and the Secret Service. As they attempted to capture Booth, the barn was set on fire, and Booth either shot himself or was killed in a shoot-out.</p>
<p>Lincoln's death stunned the country and muted its joy over the end of the Civil War. After seven days of official mourning in the Capitol, Lincoln's coffin was carried on a slow-moving funeral train back to Springfield, Illinois. As the procession traveled through the country, people in small towns and villages, in big cities, and throughout the countryside gathered to see the train pass and offer their last respects to Lincoln. Thousands of Americans remembered the sight of the passing funeral train as one of the most deeply emotional events of their lives.</p>

<p>For more information, please visit the <a href="../lincoln">Abraham Lincoln home page</a>.</p><h4>Abraham Lincoln</h4>
