
<h2>1951-04-11 12:00 PM</h2><h1>Truman Dismisses General MacArthur</h1>

<p>On April 11, 1951, President Harry Truman dismissed General Douglas MacArthur, one of the most well known and respected officers in the Army, as commander of the U.S. forces in the Korean War.</p>  
<p>MacArthur had graduated first in his class from West Point in 1903 and served with distinction in the World War I. In World War II, he was commander of U.S. forces in Asia, coordinating the island-hoping campaign against the Japanese. After the war, he remained in Japan as head of the occupation forces. When the invasion of South Korea began, MacArthur quickly requested permission from Truman to intervene. The President agreed, and MacArthur became commander of the U.S. forces in Korea, masterminding the successful landing at Inchon.</p>
<p>MacArthur, aware of his heroic reputation, created many difficulties for the Truman administration. Despite orders that all his public comments had to be approved, he frequently made statements to the press undermining Truman's foreign policy.  MacArthur often ignored suggestions made by his superiors on the Joint Chiefs of Staff.  While MacArthur was told to use caution in approaching the Yalu River, he instead quickly advanced toward the Chinese border. In December, while the Truman administration attempted to maintain a limited conflict, MacArthur recommended military action against China including a blockade and large-scale bombings.</p>
<p>The General's greatest infractions, however, occurred in March 1951. When Truman informed MacArthur that he would seek a negotiated settlement of the Korean conflict, MacArthur chose to make his own offer to meet with the Chinese. If this was not enough, MacArthur sent a letter to Republican Congressman Joseph Martin, criticizing Truman's decision to try to end the war. This was the last straw. Truman removed General Douglas MacArthur, and General Matthew Ridgeway became commander of the U.S. troops in Korea.</p>
<p>Upon his return to the United States, MacArthur received a hero's welcome. He addressed a joint session of Congress to a standing ovation and was greeted by a ticker tape parade in New York City. Despite this excitement, much of the press, many congressmen, and large segments of the public agreed with Truman's actions. Truman had upheld the constitutional supremacy of elected officials over the military and had maintained the strategy of limited war.</p> 

<p>For more information, please visit the <a href=""../truman"">Harry S. Truman home page</a>.</p><h4>Harry S. Truman</h4>