
<h1>Ku Klux Klan Bill Enacted</h1><h2>1871-04-20 12:00 PM</h2>

<p>On April 20, 1871, at the urging of President Ulysses Grant, Congress passed the Ku Klux Klan Act. Also known as the third Enforcement Act, the bill was a controversial expansion of federal authority designed to give the federal government additional power to protect voters. The act established penalties in the form of fines and jail time for attempts to deprive citizens of equal protection under the laws and gave the President the authority to use federal troops and suspend the writ of habeas corpus in ensuring that civil rights were upheld.</p>
<p>Founded as a fraternal organization by Confederate veterans in Pulaski, Tennessee, in 1866, the Ku Klux Klan soon became a paramilitary group devoted to the overthrow of Republican governments in the South and the reassertion of white supremacy. Through murder, kidnapping, and violent intimidation, Klansmen sought to secure Democratic victories in elections by attacking black voters and, less frequently, white Republican leaders. </p>
<p>In response to Klan violence, Congress passed the first of three Enforcement Acts on May 31, 1870, to ensure that the provisions of the Fourteenth and Fifteenth Amendments were followed. The act, which made it a federal offensive to try to deprive anyone of his civil rights, had little effect on the deteriorating situation. A second Enforcement Act, passed on February 28, 1871, established federal supervision over elections, but also did little to remedy the situation.</p>
<p>After the failure in the House of a more powerful bill that would have given the federal government additional power to enforce election law, President Grant decided to intervene. The President met with Congressional leaders to urge the passage of stronger legislation, and on their recommendation, Grant issued a direct appeal to Congress requesting a new law. Grant's appeal was successful, and Congress passed the Ku Klux Klan Act.</p>
<p>President Grant put the new legislation to work after several Klan incidents in May. He sent additional troops to the South and suspended the writ of habeas corpus in nine counties in South Carolina. Aided by Attorney General Amos T. Akermen and the newly created Department of Justice, extensive work was done to prosecute the Klan. While relatively few convictions were obtained, the new legislation helped to suppress Klan activities and ensure a greater degree of fairness in the election of 1872.</p>

<p>For more information, please visit the <a href="../grant">Ulysses Simpson Grant home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
