
<h2>1915-05-07 12:00 PM</h2><h1><em>Lusitania</em> Sinks</h1>

<p>On May 7, 1915, the German submarine <em>U-20</em> torpedoed the British luxury liner <em>Lusitania</em> within sight of the Irish coast. The largest passenger ship in wartime transatlantic service at the time, the <em>Lusitania</em> was struck by a single torpedo and sank in twenty minutes after a second internal explosion. Of the more than 1,900 people on board, nearly 1,200 died, including 128 Americans.</p> 
<p>After the outbreak of World War I in Europe in the summer of 1914, Britain laid a blockade upon German ports. In response, Germany deployed experimental attack submarines, called U-boats, in the Atlantic Ocean. The German government declared the waters around the British Isles a war zone in February 1915 and cautioned that its U-boats would sink any ship entering the zone without warning. Germany justified the action of unrestricted submarine warfare by claiming that Britain had violated its own freedom of the seas with the blockade. The German government also argued, correctly, that the British used neutral and civilian ships to transport munitions.</p>
<p>With the outbreak of World War I, President Woodrow Wilson led the United States in its declaration of neutrality. However, this stance began to be tested when Germany began unrestricted submarine warfare. Shortly afterwards, four American citizens were killed in three U-boat attacks. Wilson debated a proper response to German violations of American neutrality with advisor Robert Lansing and Secretary of State William Jennings Bryan. While Wilson and his advisers debated, the Germans torpedoed the <em>Lusitania</em>.</p> 
<p>The scale of the disaster shocked and enraged the American public and moved Wilson to take a defensive stand against Germany's violation of American neutrality rights at sea. The President issued a note to the German government demanding that it stop its policy of unrestricted submarine warfare and pay reparations for the deaths of those Americans lost on the <em>Lusitania</em>. The German Imperial Government defended itself by reminding Wilson that the ship had been illegally carrying contraband munitions. It claimed it was the explosion of such munitions that so rapidly sank the ship. </p>
<p>Wilson found Germany's reply unconvincing and drafted a second note over Bryan's objections that urged Germany again to respect civilian and neutrals' “rights of humanity” and warned of his will to defend his own citizens. Bryan resigned rather than sign the second note because he felt that Wilson was not balancing both British and German violations of American neutrality. He was also concerned that the President was taking too hard a stance towards Germany that would leave the United States no alternative except to enter the war. After Bryan's resignation, Wilson promoted Lansing to secretary of state and issued a third note to Berlin warning that the United States would regard another sinking of a passenger liner as a “deliberately unfriendly” act.</p> 
<p>Germany never accepted culpability for the loss of the <em>Lusitania</em>. While the German government maintained its position that it sank the ship within the conventions of war, it wanted to keep the United States from entering the war and issued secret orders to its submarine captains to stop sinking large passenger liners. Nevertheless, the <em>Lusitania</em> issue remained a lingering sore spot in American-German relations as the two nations drifted closer to war.</p>


<p>For more information, please visit the <a href=""../wilson"">Woodrow Wilson home page</a>.</p><h4>Woodrow Wilson</h4>
