
<p>/images/academic/americanpresident/essayimages/05_01.jpg</p>
<h2>1960-05-01 12:00 PM</h2>
<h1>U-2 Plane Shot Down</h1>

<p>On May 1, 1960, the Soviet Union shot down an American U-2 reconnaissance plane. The pilot Francis Gary Powers ejected from the plane and survived. The Soviets quickly took Powers prisoner and recovered the remains of the U-2 plane. Hoping to embarrass the United States, the Soviets kept the capture of Powers secret only announcing that an American plane had been shot down.</p>
<p>The administration of President Dwight D. Eisenhower hoped to avoid a conflict with the Soviet Union over the U-2 incident because the long-anticipated Paris conference between the United States, France, Britain, and the Soviet Union to discuss possible arms control agreements was scheduled to begin in mid-May. Rather than revealing that the United States had been flying U-2s over the Soviet Union since 1956 when Eisenhower had authorized the Central Intelligence Agency (CIA) to being top-secret intelligence flights over the Soviet Union, the State Department and the White House issued a series of cover stories, including one that a weather plane had been lost. The Kremlin exposed these cover stories as lies. On May 7, Soviet Premier Nikita Khrushchev scored a diplomatic victory when he revealed that the Soviets had the plane, its pilot, and proof that the United States had been spying on the Soviet Union. This announcement seriously challenged the credibility of the administration with both its allies and the American public.</p>
<p>Eisenhower now had to make a choice. He could refrain from commenting on the incident, but this would encourage rumors that he had not authorized the mission thereby weakening his political position. His other option was to take responsibility for the flights and attempt to defend his actions. On May 11, only days before the summit meetings in Paris, Eisenhower took this latter route. He announced that he had approved the flights, and he emphasized their importance to avoid “another Pearl Harbor.”  These U-2 flights were, the President concluded, “a distasteful but vital necessity.”</p>
<p>Despite the U.S. admission, the President still hoped that the summit could lead to some agreement between the Soviets and the Western powers. Khrushchev, however, remained angry about the U-2 incident. Under pressure from hard-liners in Moscow, the Soviet Premier insisted that Eisenhower end the program of U-2 flights, apologize for previous flights, and punish those responsible for the espionage. Eisenhower stated that he would halt future flights, but refused to bend to any other demands. Khrushchev stormed out of the conference, effectively ending it. The U-2 incident ended the détente in the Cold War that Eisenhower had cultivated during much of his administration.</p>

<h4>Dwight David Eisenhower</h4>
