
<h2>1846-05-13 12:00 PM</h2><h1>United States Declares War on Mexico</h1>

<p>On May 13, 1846, President James K. Polk signed a declaration of war against Mexico. Polk had submitted his war message to Congress on May 11 after General Zachary Taylor and his troops had clashed with Mexican forces on the northern bank of the Rio Grande, and Congress quickly approved the declaration of war against Mexico. After the President signed the declaration, he and his cabinet decided to conduct a three-pronged war: General Taylor would secure northern Mexico, an army under Stephen Kearny would capture New Mexico and California, and a third force under the command of Winfield Scott would capture Mexico City.</p>
<p>Kearny headed west and found New Mexico abandoned by Mexican forces. He then moved to California, capturing Los Angeles in January 1847. Taylor remained active in northern Mexico, winning several battles and capturing Monterrey, an important Mexican trade-center. Polk then ordered a large portion of Taylor's troops to Vera Cruz to bolster Scott's force for the assault on Mexico City. Hearing of Taylor's reduced forces, Mexican General Santa Anna decided to attack but Taylor and his outnumbered troops repulsed the Mexican forces at the Battle of Buena Vista. Santa Anna retreated south and was again defeated when Scott captured Mexico City in September 1847. </p>
<p>With a strong advantage in the field, Polk's diplomat Nicholas Trist attempted to arrange terms with Mexico. After several false starts, Trist on February 2, 1948 arranged the Treaty of Guadalupe Hidalgo, which ended the war. Under the terms of the treaty, Mexico agreed to recognize the Rio Grande as the Texas border and ceded California and New Mexico to the United States. The United States agreed to pay Mexico $15 million for the territories and assume $3 million in outstanding American claims against the Mexican government. The Senate approved the treaty on March 10, 1848.</p>
<p>The Mexican War was both controversial and compelling at home. Many Whigs, including a young congressman named Abraham Lincoln, objected to the war, but these dissenting voices were mostly lost underneath an outburst of nationalism that only grew more vociferous as the American victories mounted. Propelling this nationalist upsurge was the penny press, which sent war correspondents to the field and made the war the most reported in American history to that date. The press coverage made General Zachary Taylor a hero who captured the public's imagination and helped to propel him to the presidency in 1848.</p>  

<p>For more information, please visit the <a href=""../polk"">James Knox Polk home page</a>.</p><h4>James Knox Polk</h4>
