
<p>/images/academic/americanpresident/essayimages/05_15.jpg</p>
<h2>1911-05-15 12:00 PM</h2>
<h1>Standard Oil Company Dissolved</h1>

<p>On May 15, 1911, Chief Justice Edward White issued the Supreme Court's majority opinion upholding the dissolution of the Standard Oil Company. White agreed that the Standard Oil Company's business practices did violate the Sherman Antitrust Act because they were anticompetitive and abusive. However, he muted the circuit court's breakup plan for the company, allowing Standard Oil six months to spin off its subsidiaries instead of the initial three months mandated. </p>
<p>After the circuit court of St. Louis initially ruled against the Standard Oil Company, the company's lawyers prepared their appeal to the Supreme Court. With the support of President William Taft, Attorney General George Wickersham and prosecutor Frank Kellogg presented the government's case in January 1911. Mimicking Kellogg's successful argumentation in front of the St. Louis circuit court, they claimed that Standard Oil's consolidation of the petroleum industry through its trust company and its enormous size restricted interstate trade and produced a monopoly as outlawed in the Sherman Antitrust Act. Standard Oil lawyers countered that the circuit court's decree for the breakup of the company violated the due process clause of the Fifth Amendment that guaranteed freedom of contract and right to property. The company's lawyers also claimed that the oil trust was beyond the constitutional reach of the Sherman Act because the corporation engaged in production, not commerce.</p>
<p>The way Chief Justice White interpreted the Sherman Act altered the vague sweep of the legislation. The Sherman Act was worded to outlaw every single contract or arrangement that resulted in a restriction of trade. White added a rule of reason test-a centuries-old principle of common law-to his interpretation of the act. If the restrictions of trade produced by a trust were reasonable, that is, did not infringe on individual rights or the public good, then the judiciary need not dissolve the trust through the arbitrariness of the Sherman Act. Only if a trust unreasonably interfered with commerce in a way that damaged the American economy could it be dissolved. White's extraneous interpretation of the Standard Oil case considered the possibility of trusts to be socially beneficial. It also allowed the judiciary to be the ultimate arbitrator to what was a “reasonable” infringement of commerce by a corporation, a principle Justice Harlan claimed violated the intent of the Sherman Act's authors.</p>
<p>President Taft supported the decision, claiming it was not a dramatic departure from previous cases. The President had little ideologically invested in the Standard Oil case and actually supported industrial combinations. The case had been former President Theodore Roosevelt's idea and the centerpiece of his popular trust-busting campaign. Taft could not afford to break with Roosevelt on the case and so he supported the prosecution of Standard Oil for his own political gain. Taft praised the decision while progressives and Democrats attacked White's reason test.</p>

<h4>William Howard Taft</h4>
