
<h2>1869-05-10 12:00 PM</h2><h1>Transcontinental Railroad Completed</h1>

<p>On May 10, 1869, the transcontinental railroad was completed when a ceremonial golden spike was driven into the place where the two railroads met. The Union Pacific and Central Pacific railroads joined the railroad together in Promontory Point, Utah. Celebrations and special addresses took place across the nation after a telegraph message announced the event to the world.</p>
<p>Agitation for the construction of a transcontinental railroad had existed since the 1840s.  Army Topographical Engineers had proposed five separate routes during the 1850s, but sectional tensions prevented construction. The Civil War later resulted in Southern routes being removed from consideration. On July 1, 1862, President Abraham Lincoln signed the Pacific Railroad Act, calling for the construction of a railroad from the Missouri River to the Pacific Ocean. The act provided government bonds to fund the project and mandated a timetable for completing railroad mileage. The endeavor was virtually risk free for the government, as the bonds were to be repaid and mileage requirements forced the two companies building the tracks to work quickly.</p>
<p>The Union Pacific railroad began construction in Omaha, Nebraska, while the Central Pacific began in Sacramento, California. Armed guards and U.S. troops guarded the construction crews from potential Native American attacks as workers moved across the country in temporary, military style encampments. With the end of the Civil War, former soldiers often went west in search of work, helping to alleviate the lack of labor available in the region that had made large projects difficult to execute. In California, Chinese immigrant laborers provided much of the necessary manpower. A sense of competition developed between the two companies, leading to both crews working faster and at times even leading to sabotage.</p>
<p>As the project neared completion in the late 1860s, it became evident that a meeting point would have to be established, as otherwise the two companies were likely to continue building past one another. Under pressure from Congress, the meeting place was selected at Promontory Point, Utah. Railroad companies would complete additional transcontinental railroads in the following decades, although the Panic of 1873 delayed construction on those projects.</p>

<p>For more information, please visit the <a href=""../grant"">Ulysses S. Grant home page</a>.</p><h4>Ulysses S. Grant</h4>
