
<h2>1830-05-28 12:00 PM</h2><h1>Jackson Signs Indian Removal Act</h1>

<p>On May 28, 1830, President Andrew Jackson signed the Indian Removal Act, which gave the President additional powers in speeding the removal of American Indian communities in the eastern United States to territories west of the Mississippi River. The Indian Removal Act set the stage for the forced removals of the Cherokees, Creeks, and other southern Native American nations that took place during the 1830s.</p>
<p>President Jackson's annual message of December 1829 contained extensive remarks on the present and future state of American Indians in the United States. His message contained many observations, assessments, and prejudices about Native Americans that had been widely held by American policy makers since Thomas Jefferson's presidency. Jackson observed that as white settlement in the east expanded, the range for Native American hunters diminished, and that this would gradually lead to their extinction. For their own good, American Indians needed to be resettled on vacant lands west of the Mississippi River, the President argued.</p>  
<p>In Congress, debates on a bill that would authorize the removals that Jackson proposed began in late February 1830. The debates in both the Senate and the House were quite contentious. Those opposed to Jackson's plans had many reasons for concern. They felt for the Native American situation, and many pleaded eloquently for the inviolable nature of the Native American nations' sovereignty. They also did not want to alter the established practices of Native American treaty-making, and many did not like Jackson himself. Generally, those opposed to the bill constituted the emerging anti-Jackson party.  Despite the debate, the Indian Removal Bill passed the Senate at the end of April and passed the House at the end of May. </p>
<p>Officially, the Indian Removal Act did not directly remove any Native American communities; it simply provided for a government apparatus that made it much easier to do so. The act allowed the President to exchange eastern Native American lands for unsettled western lands and grant the Native American nations involved full title to this new land. Officially, such exchanges would have take place through voluntary treaties with the Native Americans themselves. To expedite matters, the federal government would pay all the costs involved; it would reimburse the Native Americans for any structures they had built on their lands, and subsidize the new Native American settlements in the West.  </p>
<p>This Indian Removal Act was Jackson's creature. He worked behind the scenes to get his friends and allies appointed to the proper Congressional committees, in order to produce a bill congruent with his desires. The new law now fully committed the United States government to a policy of Native American removal, a policy that Jackson and his allies would bring to life in the latter years of his presidency.</p>

<p>For more information, please visit the <a href=""../jackson"">Andrew Jackson home page</a>.</p><h4>Andrew Jackson</h4>
