
<h2>1883-05-24 12:00 PM</h2><h1>Opening of the Brooklyn Bridge</h1>

<p>On May 24, 1883, President Chester Arthur and New York Governor Grover Cleveland participated in the ceremonial opening of the Brooklyn Bridge. The Brooklyn Bridge was the first bridge to be built across the East River linking New York City and Brooklyn. The bridge was an engineering marvel, utilizing numerous construction techniques that had never before been attempted on such a massive scale.</p>  
<p>The original designer, John Roebling, died of an infection caused by an injury he received only days after having secured permission to begin his project. His son Washington took over, supervising the construction project that took thirteen years and more than $15 million to complete (three times as long and twice as expensive as had been anticipated). By the end of the project, Washington Roebling's health had deteriorated considerably. He, along with many of those involved in the project, had contracted decompression sickness because of working in the caissons used to form the foundations of the bridge towers. It is estimated that more than twenty men were killed during the construction of the bridge, although records are debatable.</p>
<p>Prior to the Brooklyn Bridge opening celebration, President Arthur's health had been deteriorating. (He suffered from Bright's disease, a then-fatal kidney ailment.) Still, the crowd of people who showed up for the event were unaware, and the President received a spectacular welcome. Arthur and Governor Cleveland walked across the bridge along with the 7th regiment as part of the celebration. Later that day, both personally congratulated Washington Roebling.</p>
<p>When the Brooklyn Bridge opened, it was the longest suspension bridge in the world and one of the most revolutionary structures of the era. It remains a symbol of engineering prowess.</p>

<p>For more information, please visit the <a href="../arthur">Chester Alan Arthur home page</a>.</p><h4>Chester Alan Arthur</h4>
