
<p>/images/academic/americanpresident/essayimages/06_05.jpg</p>
<h2>1947-06-05 12:00 PM</h2>
<h1>Marshall Plan Announced</h1>

<p>On June 5, 1947, Secretary of State George C. Marshall announced a plan to provide economic assistance to the devastated nations of Europe after World War II. He presented what became known as the Marshall Plan during a commencement speech at Harvard University. The administration of President Harry S. Truman hoped the plan would encourage both political and economic stability in Europe and help reduce the attraction of Communism to Europe's suffering populations.</p>
<p>In his speech, Secretary Marshall implied that funding would be available for all of Europe, including Eastern Europe and the Soviet Union, but the Soviet Union refused to participate. Administration officials recognized that Soviet rejection of aid would likely solidify the emerging division of the continent and were eager to pin the blame for that development on Moscow. Had the Soviets agreed to participate in the plan, its passage through Congress would have been much more difficult. The likelihood of Soviet participation, however, was slim. Marshall had made disbursal of American funds contingent upon European nations presenting a coordinated proposal to the United States, an approach designed to encourage greater cooperation among countries in Europe.</p>  
<p>In July, representatives from sixteen European nations attended a conference in Paris, France, to draw up a proposal for U.S. aid. The Soviets had sent a delegation to an initial meeting, but it soon departed under orders from Moscow. And despite the interest expressed by Czechoslovakia, Poland, and Romania in the aid plan, no East European nation was a recipient of American funds. In August 1947, representatives from the European nations presented a proposal for more than $20 billion of aid over four years. The Truman administration trimmed the amount to $17.8 billion before sending it Congress as the European Recovery Plan (ERP). President Truman insisted on associating the plan with Secretary Marshall not only because he believed Marshall deserved the credit, but because, given his political difficulties with Congress, he wanted to distance himself from the plan. The Marshall Plan's enormous cost led to opposition in Congress, but Stalin's aggressive actions in Eastern Europe, particularly in 
Czechosvakia, helped secure the first appropriation of $6.8 million in April 1948. By the time the Marshall Plan had come to an end in 1952, it had provided more than $13 billion in aid to Western Europe. </p>
<p>Some historians have criticized the plan for increasing tension with the Soviet Union or as a program designed to create markets for American goods in Europe. Despite these negative connotations, the Marshall Plan provided financial and humanitarian aid which fostered economic growth and political stability for the peoples of Western Europe.</p>

<h4>Harry S. Truman</h4><h4>Harry S. Truman</h4>
