
<p>/images/academic/americanpresident/essayimages/06_11.jpg</p>
<h2>1800-06-11 12:00 PM</h2>
<h1>Washington Becomes U.S. Capital</h1>

<p>On June 11, 1800, Philadelphia, Pennsylvania, ceased to be the capital of the United States, as the new city of Washington in the District of Columbia became the country's official capital. The federal government moved its offices to Washington, D.C., in June. In November, President John Adams first slept in the unfinished Executive Mansion (now known as the White House) and Congress met for the first time in the U.S. Capitol building.</p> 
<p>In 1790, Congress passed “An Act for Establishing the Temporary and Permanent Seat of the Government of the United States,” commonly known as the Residence Act. The act made Philadelphia the temporary capital for ten years and authorized the President to select a site for the nation's permanent capital along the Potomac River. As President, George Washington energetically promoted the development of his namesake city so it would be ready to receive the federal government in 1800, according to the terms of the Residence Act.</p>
<p>In 1791, President Washington asked the French engineer Pierre Charles L'Enfant to design the city. L'Enfant's plans included great public squares, extensive parks and gardens, a system of avenues radiating from the city's center, and public buildings located majestically along the Potomac. His dismissal from the project in 1792, combined with a lack of funding for construction, rendered the city woefully underdeveloped when the federal government arrived in 1800. (It was not until the twentieth century, in fact, that L'Enfant's designs for the city were gradually implemented.) At the dawn of the nineteenth century, only one wing of the U.S. Capitol building was complete, and the federal city consisted of less than 400 houses with a population of about 3,000. Roads were scarce, entertainment virtually nonexistent, and housing limited. Fewer than 300 federal personnel moved into the city. Congressmen frequently rented rooms in boarding houses two to a bed.</p>
<p>In November, President John Adams moved into the still incomplete White House, of which only the box-like center had been built. Life in the White House seemed only a slight improvement over congressmen's circumstances. John and Abigail Adams lacked an expense account to furnish the house and a staff to maintain it. Yet, they were expected to host social functions and official receptions. However, President Adams did not have to struggle under the burden for long. Just a few months after moving into the White House, he turned it over to Thomas Jefferson, who defeated him in the election of 1800.</p>
<p>Despite the initial hardships and inadequacies of the federal government's new home, a general optimism about the city prevailed. Unlike the Adamses, who were from Massachusetts, Jefferson knew the Potomac region well and had long supported its location for the nation's capital. His election, the “Revolution of 1800,” along with the rapid progression of construction in Washington, breathed life into the fledgling capital city. Jefferson's election renewed enthusiasm for the federal government and provided impetus for the further development of Washington, D.C.</p>

<h4>John Adams</h4>
