
<h1>Rosenbergs Executed</h1><h2>1953-06-19 12:00 PM</h2>

<p>On June 19, 1953, Julius and Ethel Rosenberg were executed shortly before sundown after being convicted of conspiracy to commit espionage. President Dwight Eisenhower refused to grant the Rosenbergs clemency. The Rosenberg case took place during a period of anti-Communist fervor in the United States; the Cold War had begun between the United States and the Soviet Union, and Senator Joseph McCarthy was holding hearings in the U.S. Senate to oust Communists who he believed had infiltrated the U.S. government.</p>
<p>Julius and Ethel Rosenberg were both born and raised in New York City and were members of the American Communist Party during the 1940s. In April 1951, they were convicted of passing information about the atomic bomb to the Soviet Union and sentenced to death. Their execution was postponed as they filed for appeal. In February 1952, the U.S. Court of Appeals upheld their conviction. When the Supreme Court refused to hear their case, they petitioned President Harry Truman for clemency. Truman denied their petition, leading to numerous protests and countless telegrams and letters from around the world. Many claimed that the Rosenbergs were innocent, that they had not received a fair trial, or at the very least, they did not deserve to be punished by death.</p>
<p>When Dwight Eisenhower took office in January 1953, the fate of the Rosenbergs was still undecided. That spring, the Supreme Court again declined to hear the case. Eisenhower, with advice from his attorney general, refused to grant the couple clemency unless they admitted their guilt and implicated others. As he explained in his statement to the press, he felt the Rosenbergs had "received the benefit of every safeguard which American justice can provide." Eisenhower did not take the Rosenbergs' punishment lightly, but considering that there were "millions of dead whose deaths may be attributable to what these spies have done," he felt the punishment was appropriate. Protests ensued around the world to spare the couple, but to no avail.</p>
<p>There is still some debate about the Rosenberg case. Based on previously classified documents, most historians are convinced that at least Julius Rosenberg was a spy for the Soviet Union but there is less evidence that Ethel Rosenberg was one. Some scholars still question whether execution was appropriate punishment and argue that the couple could not have received a fair trial with the anti-Communist feeling in the United States during that time. And, given the political environment of the time, it is not surprising that Eisenhower refused to pardon the Rosenbergs.</p>

<p>For more information, please visit the <a href="../eisenhower">Dwight David Eisenhower home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
