
<h1>Kennedy Gives American University Address</h1><h2>1963-06-10 12:00 PM</h2>

<p>On June 10, 1963, President John Kennedy gave a commencement address at American University. In it, he addressed relations between the United States and the Soviet Union and a nuclear test ban treaty.</p>
<p>In the aftermath of the Cuban Missile Crisis in October 1962, both Kennedy and Soviet Premier Nikita Khrushchev hoped their countries could move closer to peace. The idea of a nuclear test ban treaty originated in the administration of President Dwight Eisenhower, but the two sides never could agree on the details of a pact. At the end of 1962, Khrushchev wrote Kennedy of his desire to create such an agreement. Meanwhile, Kennedy's statements began to take a softer stance toward his Soviet adversaries.</p>
<p>The need for a nuclear test ban treaty was a critical component of Kennedy's speech at American University. This speech, however, called for more than simply a ban on atomic testing. Kennedy called for a real peace; "not a Pax Americana enforced on the world by American weapons of war." He expressed sympathy for the Soviets and their losses in World War II. Both nations shared, the President explained, a common interest in preserving the planet for future generations. Agreeing to a nuclear test ban would only be the first step toward the long-range goal of complete disarmament. After surviving one of the most dangerous moments of the Cold War, Kennedy envisioned an end to arms race.</p>
<p>Kennedy's speech led to some immediate results. Soon, a new teletype hot line was installed providing direct communication between the Kremlin and the White House.  This system would end the miscommunication that proved so dangerous in the missile crises. The President also sent a delegation to Moscow to negotiate the long-awaited nuclear test ban treaty. While the resulting agreement met the demands of neither side, the "Treaty Banning Nuclear Weapons Tests in the Atmosphere, in Outer Space, and Under Water" was a significant step in decreasing tensions between the superpowers.  After coming on the verge of violent conflict in the missile crises, Kennedy and Khrushchev attempted to foster a new period of détente.</p>

<p>To read and listen to Kennedy's address at American University, click <a href="http://millercenter.org/scripps/archive/speeches/detail/3374">here</a>.</p>

<p>For more information, please visit the <a href="../kennedy">John Fitzgerald Kennedy home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
