
<h1>Battle of Little Bighorn</h1><h2>1876-06-25 12:00 PM</h2>

<p>On June 25, 1876, Lieutenant Colonel George Armstrong Custer led a detachment of the Seventh Cavalry to attack an encampment of Sioux and Cheyenne Native Americans led by Sitting Bull on the Little Bighorn River. Custer underestimated the size of the force he attacked and was killed along with all 266 men in his detachment in the ensuing battle.</p>
<p>George Armstrong Custer graduated from the U.S. Military Academy in 1861 and proved himself an excellent cavalry commander during the Civil War. In 1874, he announced to the public that the military expedition he had led into the Black Hills had discovered gold. The Black Hills were sacred Native American territory and had been protected from white incursion by an 1868 treaty (although expeditions of Custer's type were permitted).  Custer's announcement predictably led to a rush into the area. President Ulysses S. Grant, after deciding that it would not be possible to restrain the overwhelming rush of fortune seekers to the region, pressured the Sioux to allow settlement. The affair soon led to renewed fighting between the U.S. military and the Sioux.</p>
<p>After Custer's debacle in the Battle of Little Bighorn, anti-Native American sentiment increased among the American people as the story of the Custer's "massacre" at the hands of aggressive Native Americans spread. Custer's widow Elizabeth did much to popularize a heroic image of her late husband, creating for him an almost mythic status, despite the fact that Custer's death was the result of an attack he himself had initiated. President Grant, who never had been fond of Custer, referred to the battle as "wholly unnecessary."</p>
<p>Custer's actions only exacerbated the federal government's worsening relations with Native Americans and therefore dealt a serious blow to the President. Grant had wanted to shift the federal government's Native American policy toward what he called the Peace Policy. This approach attempted to move Native Americans closer to white civilization (and ultimately U.S. citizenship) by housing them on reservations and helping them become farmers. Grant had also hoped to end outright conflict between the U.S. military and Native American, but he was ultimately unsuccessful in helping improve the lives of Native Americans through his policy.</p>

<p>For more information, please visit the <a href="../grant">Ulysses S. Grant home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
