
<h2>1948-06-24 12:00 PM</h2><h1>Soviets Begin Berlin Blockade</h1>

<p>On June 24, 1948, the Soviet Union halted all transportation by road and rail into the areas of Berlin controlled by the United States, Britain, and France. The American and British forces immediately initiated an airlift of supplies to relieve the western-controlled portions of the city.  After 321 days and 272,000 flights, the airlift succeeded when the Soviets reopened the borders on March 12, 1949.</p>
<p>After World War II, Britain, France, the United States, and the Soviet Union had partitioned Germany and its capital city of Berlin. The city lay entirely within the Soviet zone of Eastern Germany but was still divided between the four allies. In June 1948, the Western powers introduced new currency into their occupation zones, initiating the formation of a self-governing Germany.</p>  
<p>After the Soviets began the blockade of Berlin, President Harry S. Truman made the decision that the United States would "stay in Berlin" and not concede the city as part of the Soviet sphere of influence. He rejected, however, proposals to send a military convoy through the Soviet zone to Berlin, which would have most likely led to war. Instead, he chose to maintain the airlift. Some advisers doubted that an airlift would succeed in supplying the people of West Berlin with food and fuel, but Truman risked both his foreign policy objectives and his political future on supplying the city without initiating war. From the perspective of the Truman administration, losing Berlin would have undermined U.S. credibility around the world.</p>
<p>The crisis over Berlin demonstrated a high point in the tensions between the United States and the Soviet Union. Nevertheless, the airlift garnered wide public support in the United States, allowing Truman to emphasize his administration's anti-Soviet credentials during the 1948 presidential campaign. By this point, the Cold War had become a major issue both internationally and in the domestic political arena.</p>

<p>For more information, please visit the <a href="../truman">Harry S. Truman home page</a>.</p><h4>Harry S. Truman</h4>
