
<h1>President John Tyler Weds</h1><h2>1844-06-26 12:00 PM</h2>

<p>On June 26, 1844, President John Tyler married Julia Gardiner in a private ceremony at a New York City Episcopal church. It was the first time a President had wed while in office, and two days later the Tylers held a reception in the Blue Room of the White House to introduce the country to its new First Lady.</p>
<p>President Tyler's first wife, Letitia, died on September 10, 1842, becoming the first First Lady to die in the White House. She was already an invalid due to a stroke by the time she arrived in Washington, D. C., in 1841, and largely remained confined to the presidential mansion's second floor during her husband's term. Letitia Tyler made only one social appearance during her entire time in the capital. After her death, President Tyler and the nation mourned her passing.</p>
<p>But President Tyler's mourning ended just a few months later when he met Julia Gardiner in early 1843. Julia was the daughter of a prominent New York businessman, and she met the President while making the social rounds among Washington's political elite. Tyler found himself enraptured with the young lady and began to court her aggressively, proposing marriage early in their relationship. Julia at first declined, but eventually agreed.</p>
<p>Julia was thirty years younger than President Tyler, and the marriage instantly became the subject of intense gossip. Tyler's political opponents-Whigs and Democrats alike-seized upon the event as another opportunity to pummel the President. Yet the controversy did little to further damage Tyler's much-maligned reputation. He had already been passed over by the presidential nominating committees of both major parties the previous May, and the nation's political attention was fixed on the 1844 election between James K. Polk and Henry Clay. During the last eight months of his administration, Tyler and his new wife staged elaborate balls and receptions, while the public focused its attention on the 1844 presidential race. 

<p>For more information, please visit the <a href="../tyler">John Tyler home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
