
<h2>1850-07-09 12:00 PM</h2><h1>President Taylor Dies</h1>

<p>On July 9, 1850, President Zachary Taylor died after a brief illness. He had attended a ceremony at the unfinished Washington Monument on July 4. For several hours, the President sat under the blazing sun, listening to various speakers, before he took a walk by the Potomac River and retired to the White House around 4:00pm. There he drank iced water and chilled milk and ate cherries and other fruits. Taylor did not feel well that evening, but conducted business the next day.</p>
<p>By July 6, however, Taylor's family became concerned as his health deteriorated. They summoned his physician, who diagnosed Taylor's ailment as cholera morbus, a term used in the nineteenth century for various intestinal afflictions. Taylor's condition continued to worsen, and he ate ice chips to keep himself hydrated until his body began to reject all fluids. The President realized he would not survive long, summoned his wife, and spoke his last words: “The storm, in passing, has swept away the trunk . . . I am about to die-I expect the summons soon-I have endeavored to discharge all my official duties faithfully-I regret nothing, but am sorry that I am about to leave my friends.” Taylor then lost consciousness and died.</p>
<p>His funeral took place on July 13. Nearly 100,000 people stood along the funeral route to see the presidential hearse. And it was quite a sight. It was drawn by eight white horses accompanied by grooms dressed in white and wearing white turbans. Washington dignitaries, military units, the President's beloved horse “Old Whitey,” and the President's family followed the hearst. Behind them, a line of military units, officials, and citizens stretched in procession for more than two miles. His final resting place was in Louisville, Kentucky, the site of the Zachary Taylor National Cemetery and Monument today.</p>
<p>Vice President Millard Fillmore, in accordance with the precedent set by John Tyler, took the oath of office the next day. Only the second man to ascend to the White House after the death of a President, Fillmore immediately set to the task of settling the sectional conflicts that were enveloping the nation. During his short term, Taylor had opposed and impeded the passage of the Compromise of 1850. Fillmore, however, openly supported the measure, helping Henry Clay, Daniel Webster, and Stephen Douglas to pass the compromise in September 1850. Tyler's untimely death, while tragic, helped secure the passage of the Compromise of 1850, granting the nation a short reprieve from sectional conflict.</p>

<p>For more information, please visit the <a href=""../taylor"">Zachary Taylor home page</a>.</p><h4>Zachary Taylor</h4>
