
<h2>1898-07-07 12:00 PM</h2><h1>McKinley Signs Hawaii Annexation Bill</h1>

<p>On July 7, 1898, President William McKinley signed a bill that annexed the Hawaiian Islands, making them part of the United States.</p>
<p>American military victories in the Pacific during the Spanish-American War helped bring to a close almost a decade of uncertainty about the status of the Hawaiian Islands. Prominent American colonists had supported the overthrow of Hawaiian Queen Liliuokalani in early 1891, but Democratic and anti-imperialist Republican opposition to annexation blocked the island chain's incorporation into the United States. When William McKinley assumed the presidency in 1897, he reversed the policy of his predecessor, Democrat Grover Cleveland, and advocated Hawaiian annexation. McKinley, however, was unable to push a new annexation treaty through Congress that year.</p>
<p>After American forces swung into action in the Pacific during the Spanish-American War, the island chain's strategic importance became apparent. Thereafter, McKinley played a more forceful role in advocating Hawaiian annexation. He pressured senators to approve annexation as the fulfillment of American manifest destiny, as a means to cement American presence in the Pacific, and as a vital support link for America's new claim on the Philippines. McKinley also worried that the growing Japanese community on the island would lead the islands into the hands of the increasingly active Japanese Empire.</p> 
<p>An annexation resolution supported by the President made its way into the House of Representatives on May 4, 1898. The Senate passed the measure on July 6, and McKinley signed it one day later. The United States took formal possession of the islands on August 12, 1898. Hawaii's first territorial governor was posted in 1900.</p>
<p>The annexation of the Hawaiian Islands was one illustration of how the United States emerged on the world stage in new and unprecedented ways during the presidency of William McKinley. His aggressive policy on Hawaii, coupled with America's seizure of the Philippines, brought the United States squarely into the increasingly competitive realm of power politics in the Pacific.</p>

<p>For more information, please visit the <a href=""../mckinley"">William McKinley home page</a>.</p><h4>William McKinley</h4>
