<h1>Jackson Vetoes Bank Bill</h1><h2>1832-07-10 12:00 PM</h2>

<p>On July 10, 1832, President Andrew Jackson vetoed a bill that would have renewed the corporate charter for the Second Bank of the United States. It was one of the most definitive acts of his presidency.</p>

<p>The Second Bank of the United States was created in the aftermath of the War of 1812 and had been controversial throughout its life. Many people blamed the Bank for the Panic of 1819, and Westerners and Southerners felt that the Bank in general, and its lending policies in particular, favored Northern interests over their own. Although most bankers believed that the Bank of the United States had helped stabilize the national money supply and thus the overall banking and commercial environment during the 1820s, the Bank still had vociferous opponents, President Jackson foremost among them.</p>

<p>At the end of 1831, Senators Henry Clay and Daniel Webster, supporters of the Bank, convinced the Bank's president, Nicholas Biddle, to submit an early petition for the renewal of the Bank's charter to Congress. (The Bank of the United States was chartered through 1836.) They calculated that Jackson would not dare issue a veto on the eve of the election; if he did, they would make an issue of it in the 1832 campaign.</p>

<p>The petition to recharter the Bank became an instant source of controversy in Congress.  Although Jackson himself despised the Bank of the United States and had been an outspoken opponent since before he became President, many Jacksonians, especially from Eastern and Midwest states, supported the Bank. The recharter bill passed both houses of Congress. Although the bulk of Jackson's cabinet favored the recharter, Jackson vetoed the bill a week after Congress passed it.</p>

<p>Jackson explained his veto in a lengthy message, one of the most important state papers of his presidency. Attorney General Roger Taney and adviser Amos Kendall composed the bulk of the message, which emphasized a variety of reasons for the veto-some political, some ideological, some constitutional. Jackson's message labeled the Bank elitist and anti-republican. It also argued extensively that the Bank was unconstitutional and that it was neither "necessary" nor "proper" for the federal government to authorize and permit the existence of an institution so big and so powerful that only directly benefited a privileged few. Jackson thus challenged the rulings of the Supreme Court of the United States, which had held consistently that the Bank was constitutional.</p>  

<p>Jackson's Bank veto was significant, since it firmly inserted the President into the legislative process. Jackson vetoed the Bank bill not only for constitutional reasons, but also for political reasons. Previous Presidents had used the veto sparingly, only when they felt a law was unconstitutional. Jackson did not acquiesce in the Supreme Court's ruling that the Bank was constitutional; he challenged it head on. He also pointed to many non-constitutional issues in his message, which was new. Jackson's rhetoric of celebrating the role of the small farmer, the working man, and the middling artisan was also significant, since it has come to define Jacksonian Democracy for many historians. It was also a source of Jackson's broad-based appeal, which secured his reelection later in 1832.</p>

<p>To read the full text of Jackson's veto message, click <a href="/scripps/archive/speeches/detail/3636">here</a>.</p>

<p>For more information, please visit the <a href="../jackson">Andrew Jackson home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
