
<p>/images/academic/americanpresident/essayimages/07_11.jpg</p>
<h2>1804-07-11 12:00 PM</h2>
<h1>Burr Kills Hamilton in Duel</h1>

<p>On July 11, 1804, Aaron Burr and Alexander Hamilton met for duel, and Burr shot and fatally wounded Hamilton, who died the next day. The Burr-Hamilton duel stands as a vivid example that in the early republic partisan politics were also highly personal politics.</p>
<p>Hamilton and Burr had been political adversaries long before their famous duel. Hamilton, an arch-Federalist and President George Washington's secretary of the Treasury strongly distrusted his fellow New Yorker, and he worked against Federalist efforts to elect Burr over Thomas Jefferson, both Republicans, when they tied in the presidential election of 1800. Burr had served various positions in New York politics and then became Jefferson's vice president in 1801. Republicans felt he was unreliable, however, and dropped him in the next election.</p>  
<p>In 1804, Burr was running for governor of New York, and Hamilton was leading the opposition to Burr's candidacy; he spoke out against him and questioned his integrity in public. For these slights, Burr challenged Hamilton to a duel. Perceiving that not responding to the challenge would destroy his own honor and render him useless in future political service, Hamilton answered Burr. Although in this era duels were usually avoided by a series of negotiations through which both parties could restore their reputations, Burr took further offense at Hamilton's response. After about ten days of correspondence, Burr and Hamilton met on July 11, 1804, in New Jersey (New York had outlawed dueling).</p>  
<p>Hamilton had declared the previous evening his intention to fire into the air; whether or not he shot at Burr remained a point of contention for years to follow, but Burr nonetheless escaped unscathed after fatally wounding Hamilton, who died the next day.  After New York and New Jersey both issued warrants for his arrest, Burr went back to the District of Columbia and resumed his position as vice president, presiding over the Senate.</p> 
<p>As public outrage grew, Burr fled to the west, where from 1805 to 1807 he participated in a vague but ambitious plan to separate the southwest from the United States. The Supreme Court found him not guilty of treason in 1807, and after five years in Europe, Burr returned to New York, where he practiced law in New York until his death in 1836.</p> 

<h4>Thomas Jefferson</h4>
