
<h2>1955-07-18 12:00 PM</h2><h1>Geneva Convention Begins</h1>

<p>On July 18, 1955, the leaders of the United States, the Soviet Union, Britain, and France began their meetings at a Summit Conference in Geneva, Switzerland. This was the first meeting between the "Big Four" since the end of World War II. While few tangible accomplishments emerged from this summit, the meeting inaugurated a new, less hostile phase of the Cold War.</p>
<p>President Dwight Eisenhower and his advisers were hesitant about meeting with the Soviet Union. The death of Stalin in 1953 had done little to diminish the animosity between the nations. Accordingly, Washington developed a test of Soviet sincerity: if the USSR would sign a long-delayed peace treaty with Austria, Eisenhower would agree to attend a conference. Even after the Soviets passed this test, however, some members of the administration, such as Secretary of State John Foster Dulles, feared the consequences of such a meeting. Dulles counseled Eisenhower to make few concessions and to avoid friendly social interactions with his Soviet counterparts. Eisenhower partially followed Dulles's advice. He made hard-line demands on the Soviets, calling for elections in Eastern Europe and the unification of Germany. Socially, however, Eisenhower was friendly when meeting with Soviet leaders. The President's approach led to feelings of good will, but little in the way of concrete agreements.</p>
<p>One of the major sticking points for an arms control agreement was the issue of inspection. Each side needed to confirm the removal of nuclear weapons through some type of examination. In order to bypass this impediment, Eisenhower proposed an "open skies" policy, which would allow nations to inspect military installations from the air. The Soviet representatives rejected this idea, correctly viewing the proposal as a way that the Americans could gain critical intelligence.</p>			
<p>The "Spirit of Geneva" eased tensions between the Soviets and the United States, and Eisenhower returned home triumphant, even though the conference failed to produce agreements on arms control or other major international issues. The President had demonstrated that the United States was sincere in pursuing peace while remaining firm against the threats of the Soviet Union. According to a Gallup poll, Eisenhower's popularity reached 79 percent after the conference, the highest level of his presidency.</p>

<p>For more information, please visit the <a href="../eisenhower">Dwight David Eisenhower home page</a>.</p><h4>Dwight David Eisenhower</h4>
