
<h2>1979-07-15 12:00 PM</h2><h1>Carter Gives "Crisis of Confidence" Speech</h1>

<p>On July 15, 1979, President Jimmy Carter delivered what became known as his "Crisis of Confidence" or "malaise" speech to the American public on national television.</p> 
<p>In the late 1970s, the United States faced a variety of challenges, including high inflation, rising interest and unemployment rates, and an energy crisis created by dependence on foreign oil and over consumption. In response, President Carter called together a gathering of American citizens at Camp David and spoke with them, as well as with others across the nation, to gain a sense of what ordinary citizens regarded as the main problems facing the country.</p>  
<p>When Americans tuned in to watch the President on July 15, most expected a talk on the energy crisis and administration plans to address it. Carter, however, targeted broader issues. He began by acknowledging that the country faced a "fundamental threat to American democracy." The President identified the threat as a "crisis of confidence" that struck at the heart and soul of the national will. For Carter, the problem lay in the lack of respect Americans held for their public institutions and leaders. Restoring that faith and confidence, said Carter, was the "most important task" facing the nation.</p>  
<p>Although the speech also contained substantial energy proposals -increased domestic production, the restriction of foreign oil imports, and an excess-profits tax on energy income to pay for new alternative energy development- much of this was lost in the rhetoric of malaise that colored the address. That rhetoric backfired on the President. Public perceptions of Carter as weak-in effect, a belief that Carter was suffering from the very crisis he spoke about-grew, as many Americans blamed his administration for the problems he lamented. A year later, Ronald Reagan campaigned for the presidency as a strong, vigorous alternative to Carter's weakened image, and he won a landslide victory in the process.</p>

<p>To watch, listen, or read the full text of Carter's "Crisis of Confidence" Speech, click <a href="http://millercenter.org/scripps/archive/speeches/detail/3402">here</a>.</p>
<p>For more information, please visit the <a href="../carter">Jimmy Carter home page</a>.</p><h4>Jimmy Carter</h4>
