
<p>/images/academic/americanpresident/essayimages/07_24.jpg</p>
<h2>1974-07-24 12:00 PM</h2>
<h1><em>United States</em> v. <em>Nixon</em> Decided</h1>

<p>On July 24, 1974, the Supreme Court ruled in an 8-0 decision that President Richard Nixon had to turn over sixty-four tapes, which disclosed his knowledge and participation in the cover-up of the Watergate burglary. The conversations on the tapes implicated Nixon and led to his resignation, the first time in United States history a President had resigned.</p>  
<p>The Watergate scandal began when five men were arrested for breaking into the office of the Democratic National Committee on June 17, 1972. Initially it was unclear if there was any connection between the burglary and the Nixon administration but gradually it was revealed that the White House was involved.</p>
<p>Then on July 16, 1973, former White House aide Alexander P. Butterfield testified that since 1971 the White House routinely recorded conversations. The taping was undertaken ostensibly to provide a historical record of the Nixon Administration, but it soon emerged as a means to prove President Nixon's guilt or innocence.</p>
<p>When the existence of the tapes was revealed, the Senate Watergate Committee requested access to them. Unable to come to an agreement with Nixon on releasing the tapes, the Senate Committee called on the President to produce the tapes. Special Prosecutor Archibald Cox also issued a subpoena for the tapes as part of his investigation. President Nixon responded by refusing to release the tapes, claiming that his conversations were private and hence protected from forced disclosure by the doctrine of executive privilege-a concept which permits officers of the executive branch to maintain a level of privacy to promote open and vigorous debate. In his refusal, Nixon stated unequivocally that the tapes were “entirely consistent with what I have stated to be the truth.”</p>
<p>This confrontation set the stage for the <em>United States</em> v. <em>Nixon</em>, in which the Court ruled unanimously that President Nixon must turn over the tapes. Chief Justice Warren Burger wrote the decision, in which the Court upheld the doctrine of executive privilege but said it was generally limited to areas of national security or diplomatic affairs. The Court went on to say that that the President is not above the law and Nixon must turn over the tapes.</p> 
<p>Soon after the Court's decision, Nixon released the tapes. The tapes revealed that the President had participated in a cover-up of the burglary as early as June 23, 1972, just days after it occurred. The release of the tapes eroded what was left of Nixon's support.  Beginning July 27, the House of Representatives adopted three Articles of Impeachment against the President.</p>
<p>In a televised speech on the night of August 8, 1974, President Richard Nixon announced his intention to resign at noon the next day. Although he conceded he had made some wrong judgments, he did not admit to any wrongdoing. Vice President Gerald Ford was sworn in as President the next day, remarking in his inaugural address, “My fellow Americans, our long national nightmare is over.”</p>
<p>Nixon's resignation marked the first such act by a President in U.S. history. Among its many implications, the resignation confirmed that no individual-regardless of rank or station-was above the law, and that there were real consequences for those who violated the law willfully. As for its political impact, the resignation chipped away at the aura of the presidency and the public's trust in government.</p>

<h4>Richard Milhous Nixon</h4>
