
<h2>1974-08-08 12:00 PM</h2><h1>President Nixon Resigns</h1>

<p>On August 8, 1974, President Richard M. Nixon announced to a national television audience that he was resigning from the office of the presidency. Nixon's resignation came less than a month after the House Judiciary Committee voted for three articles of impeachment relating to Nixon's illegal involvement in the Watergate scandal and his use of government agencies to cover up that involvement. In the weeks prior his announcement, many loyal supporters had confidentially advised Nixon that he ought to consider resignation in order to spare the country the political trauma of an ineffective President during a long House impeachment and Senate trial.</p>
<p>President Nixon admitted to making mistakes, but not to the “high crimes and misdemeanors” alleged in the impeachment articles. Nixon decided to resign when he realized that he “no longer had a strong enough political base in Congress” to make it possible for him to complete his term in office. He thanked his friends for their support, and asked all Americans to back the new President, Gerald R. Ford, himself in office due to the resignation of former Vice President Spiro Agnew. As for his foes, the President remarked that was leaving office “with no bitterness toward those who have opposed me.” Special Prosecutor Leon Jaworski, appointed after the dismissal of Archibald Cox, announced that his investigation would continue, possibly leading to the filing of criminal charges against the ex-President. On September 8, just a month after the resignation, President Ford granted Nixon a “full, free, and absolute pardon,” ruling out any criminal prosecution of the nation's 37th President.</p>
<p>Nixon's resignation marked the first such act by a President in U.S. history. Among its many implications, the resignation reinforced the powers of the Congress and the Supreme Court to insist that the law be followed. It confirmed that no individual-regardless or rank or station-was above the law, and that there were real consequences for those who violated the law willfully. As for its political impact, the resignation seemed to chip away at the aura of the presidency, making the office seem less important and powerful for its having been tarnished during the Nixon years.</p>  

<p>To watch, listen, or read President Nixon's address to the nation about his decision to resign, click <a href=""http://millercenter.org/scripps/archive/speeches/detail/3871"">here</a>.</p>

<p>For more information, please visit the <a href=""../nixon"">Richard Milhous Nixon home page</a>.</p><h4>Richard Milhous Nixon</h4>
