
<h2>1920-08-18 12:00 PM</h2><h1>Nineteenth Amendment Ratified</h1>

<p>On August 18, 1920, the Nineteenth Amendment to the Constitution of the United States was ratified. The amendment gave women the right to vote.</p> 
<p>Women activists in the United States had agitated for equal political rights since the mid-nineteenth century. Reformers in the Progressive Era succeeded in making suffrage a significant political issue, and four western states granted women the right to vote in state constitutions. However, business groups and conservative women's organizations opposed women's suffrage and blocked federal efforts.</p>
<p>During World War I, women contributed greatly to the war effort through their labor and volunteer efforts. Women activists capitalized on women's newfound economic prominence during the war to agitate further for suffrage. Activist organizations such as the National American Woman Suffrage Association (NAWSA), which had pursued women's suffrage since 1890, connected the issue of a lasting peace with the extension of voting rights to women. As NAWSA campaigned through established political channels, the National Woman's Party (NWP) engaged in acts of civil disobedience in Washington, DC. The NWP staged hunger strikes and daily protests in front of the White House throughout 1917. Activists from NWP called President Woodrow Wilson's fight for democracy in Europe hypocritical while he denied women their voting rights in the United States. The well-publicized protests of the NWP embarrassed Wilson throughout the year.</p>
<p>By 1917, the political wind for suffrage had shifted. Thirteen additional states had passed women's voting measures, and pressure was mounting on Congress to consider a national women's suffrage amendment. President Wilson came around to the idea of a constitutional amendment for women's suffrage in 1916 when he decided that women could form a crucial voting block that would support his progressive agenda. Britain granted women the vote in 1917, adding international pressure for congressional action. When the special session of Congress sat in April 1917,  activists added voting rights to the legislative docket. After the measure bypassed the House Judiciary Committee, the women's suffrage amendment passed the House on January 10, 1918. President Wilson appeared in the Senate as the body debated a bill to advocate the passage of the amendment. The suffrage amendment fell two votes short of ratification in an October 1918 vote. Congress revisited the issue in a special session in May 1919. The amenndment passed the House on May 21 and the Senate on June 14, 1919.</p>
<p>After congressional approval, the suffrage amendment entered into a tenaciously contested battle for ratification in state legislatures. The amendment faced its greatest opposition in the South, where conservative Protestants of both genders resisted women's voting rights as a challenge to traditional values and the institution of white supremacy. States in the North and West provided the bulk of support for the amendment, but Southern support in a few states was still needed for ratification. After the thirty-fifth state ratified the amendment in early 1920, President Wilson leaned heavily on Tennessee governor Albert Roberts to call a special session of the state legislature that summer. With heavy local and national pressure bearing down on the legislature, the Tennessee legislature passed the amendment by two votes on August 18, 1920, securing its ratification as the nineteenth amendment to the Constitution.</p>


<p>For more information, please visit the <a href=""../wilson"">Woodrow Wilson home page</a>.</p><h4>Woodrow Wilson</h4>
