
<p>/images/academic/americanpresident/essayimages/08_14.jpg</p>
<h2>1935-08-14 12:00 PM</h2>
<h1>Roosevelt Signs Social Security Act</h1>

<p>On August 14, 1935, President Franklin Roosevelt signed the Social Security Act, which established a Social Security Board to coordinate the payment of old-age benefits to Americans over the age of 65.</p> 
<p>After the crash of the stock market in 1929, the United States sunk into the Great Depression. With high rates of poverty among the elderly, many people felt the government needed to do something to protect its citizens. In June 1934, President Roosevelt had created the Commission on Economic Security, which studied economic security, social insurance, and long-term relief programs. It then proposed a social security program that could help people who were retired, disabled, widowed, or unemployed. Its recommendations were to serve as the basis for legislation to be considered by Congress. The Commission formally presented its recommendations to the President in January 1935.</p>
<p>The act that Roosevelt signed included programs such as Old Age Assistance (Title I), Old Age Insurance (Title II), Unemployment Insurance (Title III), Aid to Dependent Children (Title IV), Grants for Maternal and Child Welfare (Title V) and Aid to the Blind (Title X). Taken together, these programs represented a significant commitment to developing a welfare state in the United States. Subsequent amendments to the original act added many benefits, including survivor benefits if a covered worker died prematurely, disability coverage and medical benefits.</p>
<p>The Social Security Act financed its programs through deductions from workers' paychecks, which actually stunted economic growth by muting consumer purchasing power. Moreover, the programs and benefits of the Social Security Act were not distributed evenly among all Americans. Agricultural workers (who were likely to be African Americans or Mexican Americans of both sexes) and domestic servants (often African American women) were not eligible for old-age insurance. Likewise, farm laborers were ineligible for unemployment insurance. And since state governments administered many of the Social Security programs, the size of benefits varied widely, especially between the North and the South. Still the act that Roosevelt signed in 1935 created a basis of social insurance that still exists to this day.</p>

<h4>Franklin D. Roosevelt</h4>
