
<h2>1914-08-15 12:00 PM</h2><h1>Panama Canal Opens</h1>

<p>On August 15, 1914, the Panama Canal opened to trans-oceanic traffic. Due to the outbreak of World War I earlier in the month, however, there was only modest commemoration and no official visit from President Woodrow Wilson. Only a few ships a day passed through the forty miles of locks in canal in its first few years of operation; after the World War I was over, this number increased to five thousand annually.</p>
<p>In 1903, the United States signed the Hay-Bunau-Varilla Treaty with Panama, which gave the United States perpetual control of the canal for a price of $10 million and an annual payment of $250,000. Work on the Panama Canal began in 1904. The building of the canal was originally under the direction of John Stevens. However, President Theodore Roosevelt found Stevens lacking as the head of the project and replaced him with George Goethels, who led construction to its completion. Goethels undertook a “lock-and-lake” plan for the canal route, excavating land on either side of Gatun Lake and constructing massive locks to regulate water levels rather than dig across Panama at sea level. </p>
<p>Workers cleared 50 miles of land between the Atlantic and the Pacific oceans. Using primarily the labor of blacks from the Caribbean, the American construction team excavated more than 232 million tons to create the canal path. The canal's three poured-concrete locks measured 1,000 feet long and took four years to complete. Although completed six months ahead of schedule, the project was incredibly costly in dollars and lives. The United States spent almost $400 million on construction. Nearly 30,000 workers labored ten-hour days for ten years. They toiled in dangerous conditions and beset with swarms of mosquitoes bearing malaria and yellow fever. More than 5,500 workers died during construction, including 4,500 black laborers.</p>
<p>Initial plans for a grand armada procession through the Panama Canal upon its opening in August 1914 were cancelled when war broke out in Europe on August 3. That day the cement boat Cristobal became the first ship to pass through the canal. But it was not opened to trans-oceanic traffic until the 15th. Once operational, it shortened the voyage from San Francisco to New York by more than 8,000 miles. The process of building the canal generated advances in U.S. technology and engineering skills. This project also converted the Panama Canal Zone into a major staging area for American military forces, making the United States the dominant military power in Central America.</p>

<p>For more information, please visit the <a href=""../wilson"">Woodrow Wilson home page</a>.</p><h4>Woodrow Wilson</h4>
