
<h1>March on Washington</h1><h2>1963-08-28 12:00 PM</h2>

<p>On August 28, 1963, about 250,000 people traveled to Washington, D.C., to demonstrate their support for civil rights legislation before Congress. The leaders of the major civil rights organizations led a nonviolent march from the Washington Monument to the Lincoln Memorial. Before a large crowd and a national television audience, Martin Luther King, Jr., gave his famous "I Have a Dream" speech. With a large turnout and peaceful demonstration, the civil rights leaders increased the pressure on Congress and President John Kennedy to pass meaningful civil rights legislation.</p>
<p>Before the summer of 1963, the Kennedy administration had disappointed many of those involved in the civil rights struggle. The President had often attempted to avoid conflict with Southern Democrats on issues regarding race. On June 11, 1963, after Governor George Wallace tried to block desegregation at the University of Alabama, Kennedy made his most aggressive statement on civil rights in an impromptu address to the nation, arguing on moral grounds for equal rights for all Americans. With a firm commitment to legislation for civil rights, President Kennedy met with African American leaders to gain their support. Despite Kennedy's opposition, many of the leaders at this meeting proposed a march on Washington to pressure Congress to pass a strong civil rights act.</p>
<p>The march created a moment of unity among the fractured civil rights organizations. They emphasized the peaceful and orderly nature of the march; there would be no civil disobedience. The focus of the day would be a rally in front of the Lincoln Memorial with singers and speakers, including John Lewis of the Student Nonviolent Coordinating Committee (SNCC) and Roy Wilkins of the National Association for the Advancement of Colored People (NAACP). Martin Luther King, Jr., was scheduled to speak last. He began speaking from the written text he had completed the night before, but soon drifted off onto a theme he had spoken of several times. "I have a dream," he declared, "that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character." King continued to give his most famous address presenting a vision of racial equality and harmony for the nation.</p>
<p>After the march, the organizers met with President Kennedy. King, Wilkins, and others pressed the President for a more aggressive civil rights bill and discussed strategies to garner political support. Despite the success of the march, the civil rights bill moved slowly through Congress. However, the actions of King and other activists had an important effect on President Kennedy as his administration lobbied in support of the civil rights bill. After Kennedy was assassinated, President Lyndon Johnson continued to work for civil rights legislation. On July 2, 1964, he signed the Civil Rights Act, which ended segregation in public facilities.</p>

<p>To read and listen to the full text of President Kennedy's June 11, 1963 speech, click <a href="http://millercenter.org/scripps/archive/speeches/detail/3375">here</a>.</p>

<p>For more information, please visit the <a href="../kennedy">John Fitzgerald Kennedy home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
