
<h1>British Troops Set Fire to White House</h1><h2>1814-08-24 12:00 PM</h2>

<p>On August 24, 1814, during the War of 1812, British troops invaded Washington, D.C., and set the White House, the Capitol, and other federal buildings on fire. The city had been evacuated before the British arrived with President James Madison and his administration leaving the capital city to flee the invading soldiers.</p> 
<p>During the war, British and American troops clashed up and down the East Coast, from Canada down to New Orleans. The war began after President Madison requested a declaration of war from Congress to protect American ships on the open seas and to try to stop the British practice of impressments, the seizure of U.S. sailors for service in Britain's Navy.</p> 
<p>The first years of the war proved disastrous for the United States. By the fall of 1812, the British had defeated American forces in Detroit and in western New York; in fact much of the Northwest Territory had fallen to the British. The Americans began to have military success in the spring of 1813 when the U.S. Navy defeated the British fleet on Lake Erie and U.S. forces sacked the Canadian capital in York. The United States also won significant battles against Native Americans in Ontario and the Mississippi Territory.</p>  
<p>Events swung back against the Americans in the late spring on 1814 as the British went on the offensive. British ships raided American ports from Georgia to Maine. After they landed in the Chesapeake Bay, British troops began to march towards Washington, D.C. They encountered little resistance along the way. James Monroe, who served as Madison's secretary of state and of defense, led a scouting party to report on the British advance. He sent word to President Madison that the British were marching toward Washington, D.C., and Madison and other government officials left the city for the countryside.</p> 
<p>First Lady Dolley Madison resisted the calls to evacuate. When she finally left, she made sure that a portrait of George Washington by Gilbert Stuart was removed from the White House and stored safely. She also took several important cabinet documents with her when she departed. As the British troops headed toward to capital, Monroe stayed to help with the city's evacuation. Once the British troops entered the city, they torched the White House and most other federal buildings in retaliation for the burning of the Canadian Parliament buildings in York.</p> 
<p>The United States was ultimately victorious in the War of 1812, and the Treaty of Ghent was signed by both countries in December 1814. Washington, D.C., was gradually rebuilt. It took three years to rebuild the White House, and in October 1817, President James Monroe moved back into the reconstructed White House.</p>  

<p>For more information, please visit the <a href="../madison">James Madison home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
