
<h1>Ford Pardons Nixon</h1><h2>1974-09-8 12:00 PM</h2>

<p>On September 8, 1974, President Gerald Ford granted a "full, free, and absolute pardon" to former President Richard Nixon.</p>
<p>When Ford took the oath of office just a month earlier, he took over the presidency from an embattled Richard Nixon, who had just resigned as the 37th President of the United States due to the myriad of political and legal problems surrounding his involvement in the Watergate scandal. Ford spoke to the nation on August 9, engaging in "a little straight talk among friends," and acknowledged the special circumstances of the occasion. Addressing the Watergate scandal directly, he declared that "our long national nightmare is over."</p> 
<p>Yet one month later, the President confronted the specter of Richard Nixon, a likely criminal defendant in U.S. courts for his role in that same national nightmare. When President Ford addressed the nation on September 8, he used a Sunday morning broadcast to minimize the political impact of his message. He recounted the nature of the Watergate scandal that had polarized the country. He also considered the difficulties Nixon would face in receiving a fair public trial and the potential for delayed and elaborate litigation against a former President. More importantly, he believed that the immediate needs of the country demanded an end to the Watergate controversy. His duty to ensure "domestic tranquility" and to use every means to secure it, as well as his belief that Nixon had suffered the ultimate humiliation due to his resignation, led him to grant a "full, free, and absolute pardon unto Richard Nixon for all offenses against the United States."</p>  
<p>Instead of bringing the nation together, however, the pardon reignited the firestorm surrounding Nixon. Ford's approval ratings dropped dramatically, and he would later admit that the pardon was his most difficult domestic decision. Nevertheless, the use of the pardon to forestall the prosecution of an unindicted, private citizen enhanced those powers delegated to the President under Article II, Section 2 of the U.S. Constitution and reaffirmed the use of the presidential pardon, extending its reach beyond both legal and congressional challenge.</p>

<p>For more information, please visit the <a href="../ford">Gerald Rudolph Ford home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
