
<h1>Wilson Embarks on League of Nations Tour</h1><h2>1919-09-3 12:00 PM</h2>

<p>On September 3, 1919, President Woodrow Wilson boarded a train to begin a transcontinental speaking tour to try to build support for the League of Nations and the Treaty of Versailles, which ended World War I. He gave his first speech in Columbus, Ohio, on September 4.</p>
<p>President Wilson had traveled to Europe in December 1918 to attend the Paris Peace Conference with representatives from Britain, France, and Italy. Germany signed the Treaty of Versailles on June 28, and Wilson returned to the United States on July 8. Two days later, he submitted the Treaty of Versailles to the Senate for ratification. Senatorial approval of the treaty faced an uphill battle. A number of senators remained skeptical of the League of Nations Covenant contained with the treaty. To make matters more difficult for the President, Republicans had regained control of both houses of Congress in 1918.</p>
<p>Senate resistance to the treaty came from a variety of sources. So-called "irreconcilable" progressive senators like Idaho's William Borah and California's Hiram Johnson rejected the treaty as a mechanism to preserve the British Empire through the League of Nations. Midwestern progressives like George Norris and Robert LaFollette, with large German constituencies, recoiled against the treaty's punitive measures. Senator James Reed of Missouri complained that the equal representation that all nations enjoyed in the League's assembly placed control of the body in the hands of the racially unfit.</p>
<p>The most damning opposition to the treaty, however, came from Senator Henry Cabot Lodge of Massachusetts, the chairman of the Senate Foreign Relations Committee. Lodge despised Wilson's idealism and attacked Article 10 of the League of Nations Covenant. Article 10 held members to a collective security agreement, and Lodge believed it was an indefensible infringement of American sovereignty. Lodge argued that the Senate should only ratify the treaty if it were modified to operate within the checks and balances system of the Constitution of the United States. He also insisted that implementing the collective security clause of the League Covenant required congressional approval as did declarations of war.</p>
<p>President Wilson headed out on his speaking tour against his doctors' wishes and the advice of some of his political advisers to try to win public support for the treaty and thus pressure senators to approve it. Over a period of three weeks, Wilson made forty addresses on the importance of the League of Nations, traveling to more than twenty-nine cities and covering a distance of almost 10,000 miles. The President rightly believed that the majority of the country supported both the peace treaty and the League of Nations but his speaking tour was unable to build any political momentum for ratification. Exhausted and worn out from his arduous journey, the President collapsed in Pueblo, Colorado, on September 25. He cut his tour short and headed back to Washington. Wilson suffered a serious stroke on Oct 2.</p> 
<p>Wilson's Herculean efforts were not enough to make a dent in the considerable coalition of critics in the Senate. On November 19, the Senate rejected the treaty 38 to 53. Wilson's stroke prevented him from participating in a compromise treaty, and the Senate approved a separate peace treaty with Germany in July 1921. By not ratifying the Treaty of Versailles and rejecting the League of Nations Covenant, the Senate illustrated the strong feeling of isolationism that existed in the United States after World War I.</p> 

<p>For more information, please visit the <a href="../wilson">Woodrow Wilson home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
