
<p>/images/academic/americanpresident/essayimages/09_18.jpg</p>
<h2>1850-09-18 12:00 PM</h2>
<h1>Fillmore Signs Fugitive Slave Act</h1>

<p>On September 18, 1850, President Millard Fillmore signed into law the Fugitive Slave Act, which enacted strict provisions for returning runaway slaves to their owners.</p>  
<p>The act was part of the Compromise of 1850, which was designed to ease sectional conflict between the North and South, but the inclusion of the Fugitive Slave Law made that nearly impossible. Southerners and their allies in Congress designed the Fugitive Slave Law to end Northern interference in the capture and return of fugitive slaves. The law decreed that runaway slaves apprehended anywhere in the United States had to be returned to their masters if new federally appointed commissioners decided that they were in fact fugitive slaves. It denied any due process to such slaves and allowed authorities to arrest African American suspects and return them to slave territory–whether the arrested person was an actual slave or not. Finally, it empowered federal marshals to enforce the law. The Fugitive Slave Law also cited severe penalties for noncompliance.</p> 
<p>The Fugitive Slave Act ignited a firestorm of protest across the North from both activists and the general public. Many Northerners who had previously paid little attention to slavery became stanch opponents after the passage of the law. Most importantly, the act greatly increased sectional animosities and renewed interest in antislavery politics in the North in the 1850s.</p>
<p>Fillmore personally opposed slavery but signed the Fugitive Slave Law for two reasons. First, he believed the South would secede if its demands, including a fugitive slave law, were not met. Second, Fillmore believed he could use the Compromise to unite the Whig Party behind a single national platform. Fillmore, a Whig from New York, tried to press other Northern Whigs to support the Compromise and the Fugitive Slave Law.  He worked to prevent Northern Whigs who opposed the Fugitive Slave Law from winning elections and used his patronage powers to appoint pro-Fugitive Slave Law political allies to federal office.</p>
<p>While Fillmore's support for the Compromise of 1850 helped stall the Southern secessionist movement, his efforts to unite the Whigs behind the Compromise failed, in large part because of the Fugitive Slave Law. Antislavery Whigs, who thought the law unjust, refused to support Fillmore for President in the 1852.  The Fugitive Slave Law, moreover, only deepened existing, and eventually fatal, divides within the Whig Party over slavery.</p> 

<h4>Millard Fillmore</h4>
