
<h3>Washington's Farewell Address</h3><h2>1796-09-19 12:00 PM</h2>

<p>On September 19, 1796, newspapers around the country published President George Washington&rsquo;s Farewell Address. In his address, Washington summarized his presidential tenure, cautioned against political divisions, and advised future American leaders to minimize connections with foreign powers.</p>
<p>President Washington, after nearly eight years as the nation&rsquo;s first President, determined that he would not accept a third term in office. By this time, political divisions between Alexander Hamilton on one side and James Madison and Thomas Jefferson on the other had hardened into proto-political parties. Whereas in 1789, at the time of Washington's inauguration, loyalty to country and Constitution equated with loyalty to the President, the rise of political parties had begun to separate the two. Washington, as a result, faced increasing criticism of his domestic and foreign policies during his second term. Upon deciding to retire, he offered his Farewell Address both as a defense of his presidency and a plea for the future of the federal government.</p>
<p>Washington released his farewell in the nation&rsquo;s newspapers in September 1796; he never presented it in person before any assembly. The President opened with a tribute to the people of the United States and with an explanation that his time for retirement had come. He then emphasized the importance of union and the need to avoid sectional and factional divisions. He also warned the country against permanent alliances with foreign nations.</p> 
<p>Both points responded to issues in his presidency. Washington felt betrayed by the partisan criticism of his leadership and equated lack of support for his administration with lack of commitment to the Constitution. His address thus sought to vindicate his leadership, as well as promote harmony in future governance. One policy that had been criticized by the Jefferson-led opposition involved relations with revolutionary France. Washington issued a proclamation of neutrality in 1793 upon the resumption of conflict between France and Britain. Jeffersonians argued this violated the French-American Treaty of 1778 whereby each nation pledged to assist the other. Washington feared involvement in European conflicts would jeopardize the stability of the fledgling United States, and in his farewell attempted to justify his neutrality policy.</p>
<p>Preliminary drafts of the Farewell Address revealed Washington&rsquo;s bitterness over the political climate in 1796. Revisions by Alexander Hamilton softened many of the complaints and omitted the self-pitying passages. Even so, when placed in the context of the times, the farewell reads as a lament, an ambiguous end to the first President&rsquo;s career. It illustrates Washington&rsquo;s belief in the central importance of the presidency, yet at the same time demonstrates that as early as 1796, the emerging political system had begun to shape, constrain, and frustrate the executive.</p>

<p>To read President Washington&rsquo;s Farewell Address, click <a href="http://millercenter.org/scripps/archive/speeches/detail/3462">here</a>.</p>

<p>For more information, please visit the <a href="../washington">George Washington home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
