
<h1>Terrorist Attacks</h1><h2>2001-09-11 12:00 PM</h2>

<p>On September 11, 2001, the United States endured a deadly attack when terrorists hijacked four planes and crashed them. The hijackers intentionally flew the first three planes into important targets: both towers of the World Trade Center in New York City and the Pentagon building in Washington, D.C. The fourth plane, which some speculated was headed for the White House, crashed in Somerset County, Pennsylvania. Passengers aboard the plane, talking on their cell phones, learned what the hijackers intended to do and with astonishing heroism tried to overtake the hijackers, saving the fourth target and sacrificing their lives.</p> 
<p>Police and fire department personnel in New York City rushed into the twin towers of the World Trade Center after the planes crashed into them to begin rescuing victims from the burning towers. Their colleagues assisting matters outside-like all Americans-were shocked and horrified to see those towers collapse, killing hundreds of the rescue workers and thousands of people who had been trapped inside. Total casualties from September 11, 2001, were nearly 3,000 people.</p>  
<p>President George W. Bush spoke passionately of our "disbelief, terrible sadness andquiet, unyielding anger." He pledged that the government would bring the persons responsible for the hijacking to justice. It soon became clear that Al Qaeda, a loosely-knit radical Islamic organization, was responsible for the attacks. Al Qaeda's founder was former Saudi citizen and millionaire Osama bin Laden. After Afghanistan's ruling elite-the Taliban-refused to surrender bin Laden, who was a guest in their country, President Bush swiftly gathered international support for the use of military force in Afghanistan to shatter the strength of Al Qaeda.</p>
<p>September 11, 2001, is a date that no American is likely ever to forget. Many Americans spent the day glued to their televisions, as terrible images of lives lost and property destroyed marched across the screens. Mingled with those pictures were others, equally memorable: scenes of magnificent courage, sacrifice, and hope. As a defining moment in modern United States history, September 11, 2001 has justly been compared with December 7, 1941, the day the Japanese attacked Pearl Harbor. The words of President Franklin Roosevelt more than half a century ago are most appropriate: it is a date that surely will live in infamy.</p>

<p>For more information, please visit the <a href="../gwbush">George Walker Bush home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
