
<h2>1901-09-14 12:00 PM</h2><h1>President McKinley Dies</h1>

<p>On September 14, 1901, President William McKinley died, eight days after he was shot by an assassin. He had served only six months of his second presidential term before his death.</p>
<p>After vacationing in Canton, Ohio, in the summer of 1901, President McKinley and his staff set off for the Pan-American Exposition in Buffalo, New York. On September 5, McKinley delivered a speech to a crowd of nearly 50,000 on his policy goals for his second term; his particular focus was on the promotion of American foreign trade.</p>
<p>The next afternoon, the President attended a public reception at the Exposition's Temple of Music, accompanied by three secret service bodyguards. Despite pleas from his secretary that security was inadequate for such a setting, McKinley entered the hall at four o'clock and began greeting festival patrons. Minutes later, Leon Czolgosz, a Polish-American anarchist, fired two shots at the President from close range as McKinley reached to shake the man's hand. One bullet lodged in McKinley's stomach while the other ricocheted off a button. As the crowd pounced on Czolgosz, McKinley pleaded that they not harm him. Czolgosz later confessed to shooting the President and was executed in October 1901.</p>
<p>President McKinley was taken away to a hospital in Buffalo where doctors failed to find the bullet in his abdomen. His wound became infected and developed gangrene, and his condition worsened over the course of the next week. McKinley died early in the morning of September 14, and that afternoon Vice President Theodore Roosevelt arrived in Buffalo to take the presidential oath of office. </p>
<p>The nation entered a month of mourning following McKinley's funeral in Canton on September 19. The former President was warmly remembered at the time of his death, with his hometown erecting a monument to him in 1907. McKinley was the first President since James Garfield to be assassinated and, like Garfield, his legacy faded from public memory-all the more quickly, in fact, since he was succeeded by the ebullient, reform-minded Theodore Roosevelt.</p>

<p>For more information, please visit the <a href="../mckinley">William McKinley home page</a>.</p><h4>William McKinley</h4>
