
<h2>1806-09-23 12:00 PM</h2><h1>Lewis and Clark Expedition Arrives Back in St. Louis</h1>

<p>On September 23, 1806, Meriwether Lewis and William Clark arrived back in St. Louis two-and-a-half years after they began their expedition to explore the Louisiana Territory and the Pacific Northwest. President Thomas Jefferson commissioned the expedition, which is often considered one of the greatest exploratory quests in U.S. history.</p>
<p>Well before President Jefferson purchased the Louisiana Territory from France, Americans had been curious about the lands west of the Mississippi River. Jefferson saw the West as a great collection of scientific specimens and a vast expanse that enhanced American security, but he also shared the commercial interest of American traders looking for a viable route to the Pacific Ocean. Even before negotiations to purchase New Orleans had commenced, Jefferson planned an expedition to the Pacific Northwest.</p>  
<p>In January 1803, the President asked Congress for a secret appropriation of $2,500 for the secretly planned exploration. Despite Spain&rsquo;s displeasure at U.S. hints that it would trek into French and Spanish territory, Jefferson appointed Meriwether Lewis and William Clark to lead the expedition. Lewis, the President&rsquo;s personal secretary, was merely 28 years old but had extensive knowledge of the West. He was commissioned an Army officer and given joint command with William Clark, also an Army officer. Jefferson instructed Lewis and Clark to find a path to the Pacific Ocean, preferably via water, learn the geography of the territory, explore trade with Native Americans, and return with samples of unknown species of flora and fauna. His instructions, drafted in June 1803 before the purchase of Louisiana but with knowledge the transaction would likely occur, were implemented the following year.</p>
<p>Lewis and Clark left St. Louis on the Missouri River in May 1804 with a company of nearly fifty men. The Corps of Discovery voyaged up the Missouri to North Dakota, where they spent the winter before pushing on over the Rocky Mountains to the Columbia River and Pacific Ocean. When they returned to St. Louis in September 1806, they brought samples of plant and animal species Jefferson had requested and reports that Jefferson's purchase had been well worth the price.</p>  

<p>For more information, please visit the <a href=""../jefferson"">Thomas Jefferson home page</a>.</p><h4>Thomas Jefferson</h4>
