
<h3>Meredith Arrives at University of Mississippi</h3><h2>1962-09-30 12:00 PM</h2>

<p>On September 30, 1962, an African American college student, James Meredith, arrived at the University of Mississippi, escorted by federal marshals, to attend class. They were met by an angry crowd of students and other local whites who opposed Meredith's efforts to integrate &ldquo;Old Miss.&rdquo; The deadly riot that broke out forced President John F. Kennedy to intervene, and the episode helped change the President&rsquo;s approach to civil rights.</p> 
<p>Meredith applied for admissions to the all-white University of Mississippi in early 1962. After being rejected due to his race, Meredith sued the University in federal court. On September 13, the Fifth Circuit Court of Appeals overturned Meredith&rsquo;s rejection from the University and ordered that he be immediately enrolled. Governor Ross Barnett of Mississippi announced his opposition to the ruling and pledged that &ldquo;Old Miss&rdquo; would not be integrated. Meanwhile in Washington, D.C., the President and Attorney General Robert Kennedy discussed how they could enforce the decision of the court with as little conflict as possible.</p>
<p>Robert Kennedy remained in contact with Governor Ross throughout the crisis over Meredith&rsquo;s admission. The Kennedy administration followed a federalist doctrine that local police forces should maintain law and order in these situations. They also believed that behind-the-scenes negotiations with Barnett could lead to a political compromise that would satisfy all parties involved. Reaching an agreement between Kennedy and Barnett proved difficult, however. The President wanted to avoid the imposition of military power that would remind southerners of Reconstruction, and the governor would only back down if he could blame the desegregation of Old Miss on the federal government. Despite these obstacles, the Kennedys believed Barnett had committed his state to maintaining order on the campus of Old Miss.</p> 
<p>On Sunday, September 30, when Meredith arrived along with a small contingent of federal marshals, an angry crowd of students and other local whites met them. Soon, shots were fired, killing two men. Fearing more violence, the President refused to allow the marshals to fire their weapons. Finally, at 10 p.m. the administration ordered Army units stationed in Memphis, Tennessee, to the campus. Due to a series of errors, the Army did not arrive until 2:15 am the next day. Twenty-three-thousand soldiers then restored order to the Old Miss campus and the town of Oxford. Later that morning, James Meredith escorted by a military guard attended his first class at the University of Mississippi.</p>
<p>By the time Meredith became the first African American to graduate from Old Miss in 1963, he had become an important symbol of the Civil Rights Movement in Mississippi and throughout the South. For the Kennedy administration, the incident provided several important lessons. First, it brought into question their respect for federalist doctrine.  Their trust in local law enforcement had led to a deadly race riot. Second, they questioned the ability to solve these difficult issues through negotiations with politicians. Barnett demonstrated the ability of southern Democratic politicians to make certain commitments to the President, while taking a different stand with the people of his state. Without making any specific changes in policy, the desegregation of Old Miss led Kennedy to question his administration&rsquo;s approach to civil rights.</p>

<p>For more information, please visit the <a href="../kennedy">John Fitzgerald Kennedy home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
