
<p>/images/academic/americanpresident/essayimages/10_08.jpg</p>
<h2>1888-10-08 12:00 PM</h2>
<h1>Cleveland Signs Chinese Exclusion Act</h1>

<p>On October 8, 1888, President Grover Cleveland signed the Chinese Exclusion Act, which restricted Chinese immigration to the United States. The law prohibited Chinese immigrants who returned to China from coming back to the United States. President Chester Arthur passed the first bill limiting Chinese immigration in 1882, and the federal government did not eradicate barriers to Chinese immigration until 1943.</p> 
<p>During the 1880s, racial tension on the West Coast between whites and Chinese laborers put significant pressure on the U.S. government to place restrictions on Chinese immigration. This pressure resulted in an outright ban on immigrant Chinese laborers in the Chinese Exclusion Act of 1882. But this ban was not enough to quell the growing anti-Chinese sentiment, which erupted in riots in Rock Springs, Wyoming, and Tacoma and Seattle, Washington in 1885. In 1887, Secretary of State Thomas F. Bayard began negotiations with China to produce a treaty banning the immigration of Chinese laborers to the United States. The treaty he produced in 1888 created a new twenty-year ban on the immigration of Chinese laborers, prohibited Chinese residents of the United States from reentry if they returned to China, and paid an indemnity to China as compensation for Chinese immigrants killed in the riots of 1885.</p>
<p>President Grover Cleveland welcomed immigrants who he thought would be willing to adopt Western culture and assimilate into American society, but he had little tolerance for those who he believed would not. While Cleveland had wanted to ensure that Chinese immigrants were safe from attack, he grew more and more supportive of a ban on Chinese immigration as he came to believe that the differences between Chinese and American culture were too great, and anti-Chinese sentiment in America too strong, to permit assimilation. The Senate did not ratify the 1888 treaty, due to unwillingness to appropriate funds for the indemnity and a desire among many to block the 20,000 Chinese U.S. residents who had gone to visit China from returning to America. In addition, the Chinese government had become reluctant to finalize the treaty, wanting to reduce the length of the immigration ban and reconsider the reentry agreement.</p>
<p>Cleveland, possibly motivated by the coming election, encouraged Congressman William L. Scott to propose a bill to prohibit the return of Chinese immigrants who went back to China. The bill quickly passed through Congress. Cleveland, referring to attempts to assimilate Chinese immigrants into American society as “unwise, impolitic, and injurious to both nations,” signed the Chinese Exclusion Act of 1888 into law.</p>

<h4>Grover Cleveland</h4>
