
<h2>2001-10-07 12:00 PM</h2><h1>Operation Enduring Freedom Begins</h1>

<p>On October 7, 2001, President George W. Bush announced that the United States had begun military action in Afghanistan. The military operation was code-named Enduring Freedom.</p>
<p>"On my order, U.S. forces have begun strikes on terrorist camps of Al Qaeda and the military installations of the Taliban regime in Afghanistan," Bush said in a somber, televised address from the White House Treaty Room. The air assaults, he said, were joined by Britain, with assorted intelligence efforts and logistical support coming from several other nations, including France, Germany, Australia, and Canada.</p> 
<p>The United States had turned its attention to Afghanistan shortly after the September 11 terrorist attacks because the Taliban regime had provided sanctuary to Al Qaeda, the terrorist organization responsible for the attacks. The United States demanded that the Taliban surrender Osama bin Laden, the leader of Al Qaeda. When the Taliban refused, the United States together with allies launched an attack against the Taliban.</p> 
<p>Apparently anticipating a U.S. attack, Al Qaeda had, a few days before the attacks, assassinated Ahmad Shah Massoud, the leader of an anti-Taliban rebel force known as the Northern Alliance. It was widely believed that without Massoud, the Northern Alliance would fracture as a fighting force. Instead, the Northern Alliance fought against the Taliban, bolstered by U.S. warplanes and U.S. Special Forces. First it ousted the Taliban from the city of Mazar Al-Sharif on the northern frontier and then from the capital city of Kabul. By mid-March 2002, the Taliban had been removed from power, and the Al Qaeda network in Afghanistan was severely damaged.</p>
<p>A fledgling democracy was installed in Afghanistan, but even before that country was truly pacified, the Bush administration had turned its attention to Iraq and its dictator Saddam Hussein. With U.S. attention diverted, Afghanistan was left in a precarious state, threatened by instability, violence, and a possible Taliban resurgence.</p>  

<p>For more information, please visit the <a href="../gwbush">George Walker Bush home page</a>.</p><h4>George Walker Bush</h4>
