
<p>/images/academic/americanpresident/essayimages/10_02.jpg</p>
<h2>1889-10-02 12:00 PM</h2>
<h1>Pan-American Conference Begins</h1>

<p>On October 2, 1889, the first Pan-American Conference began in Washington, D.C. The conference was a meeting between the United States and various countries in Latin America. Its goal was to improve economic and political relations between participants.</p>
<p>Secretary of State James Blaine had first proposed a Pan-American Conference in 1881 during his brief tenure under President James Garfield. After Garfield's assassination and Blaine's subsequent resignation, President Chester Arthur's secretary of state, Frederick Frelinghuysen, cancelled the conference. After the cancellation, President Arthur appointed a commission to investigate the possibility of holding such a conference, and the commission's findings favored the scheduling of a new conference.</p>
<p>President Grover Cleveland and Secretary of State Thomas Bayard did not support the idea of a conference, but on May 10, 1888, Blaine's initial proposal was revived and the conference was scheduled. Blaine was again secretary of state when the conference took place on October 2, 1889, during the administration of President Benjamin Harrison. Harrison and Blaine hoped to reach agreements at the conference to create a customs union for free trade and establish a system for arbitration of international disputes.</p>
<p>Although the Pan-American Conference convened in Washington, D.C., the participants from eighteen countries quickly left the capital to tour the industrial centers of the United States. The negotiations began when the conference reconvened in Washington in November. Secretary of State Blaine did not give instructions to the U.S. delegation, making the discussions difficult. Many South and Central American nations did not trust the United States and thought the customs union was a plan unilaterally favorable to the Americans. In addition, the U.S. delegates had trouble negotiating the customs union for free trade due to the embarrassing fact that the Republican-controlled Congress was simultaneously working on legislation to strengthen tariffs.</p>
<p>The final agreement failed to establish the customs union; delegates instead settled for a clause that encouraged reciprocity agreements. The issue of arbitration was also not resolved because the Latin American countries viewed the U.S. proposals as a violation of sovereignty. A relatively weak system, signed by fewer than half of the delegations, was established that allowed nations to refuse any arbitration that they felt threatened independence. The conference did set up the International Bureau of American Republics, also known as the Pan-American Union, to hold additional meetings in the future. The conference ended with mixed results, and another Pan-American Conference was held in Mexico City in 1901.</p>

<h4>Benjamin Harrison</h4>
