
<h2>1993-10-03 12:00 PM</h2><h1>Battle of Mogadishu</h1>

<p>On October 3, 1993, U.S. special forces stormed a compound in Mogadishu, Somalia, in order to capture aides to warlord Mohammed Farah Aidid. Commanders intended the attack to be swift and precise, but the operation quickly became a nightmare. Hostile Somalis shot down two hovering combat helicopters. U.S. ground forces were assaulted as they tried to leave town and ambushed as they attempted to reach the crews of the downed helicopters. With exits to the city blocked, and an increasing number of killed and wounded, American soldiers were forced to hunker down and await reinforcements. In the end, eighteen U.S. troops died, and eighty-four were wounded. America was left with horrific images of soldiers' bodies being dragged through the streets and angry questions as to how such a disaster could have occurred.</p> 
<p>The U.S. presence in Somalia dated from December 1992. Then-President George H.W. Bush envisioned that “Operation Restore Hope” would be limited to humanitarian assistance and would ideally conclude sometime in early 1993, time enough to have put Somalia on the road to recovery from famine and civil war. Nevertheless, the operation became more complex than anyone imagined. Leaders at the United Nations became convinced that Aidid, who had resisted political reform both prior to and following the recent introduction of UN personnel, was largely responsible for the harassment and killing of peacekeeping forces and humanitarian workers. In the end, they sought to remove him from scene.</p>
<p>When President Bill Clinton came into office, his administrative team sought to scale back the venture in Somalia. Calls from Congress and Pentagon officials, urging the President not to expand “Operation Restore Hope,” contributed further to a more circumscribed approach. Defense Secretary Les Aspin thus rejected requests from local commanders for more troops and vehicles, confident that U.S. forces would not attempt operations exceeding existing capabilities.</p> 
<p>The Battle of Mogadishu, however, led President Clinton not just to draw down but to end the U.S. presence in Somalia. Clinton's actions generated criticism from those who thought he should have carried through and captured Aidid-that he had simultaneously dishonored the soldiers' deaths and harmed American military credibility. The affair contributed to the perception that the President lacked foreign affairs expertise. Many became skeptical of the idea that the United States could or should serve as a post-Cold War, peacekeeping nation-builder, particularly under the direction of the United Nations. Regardless, the Battle of Mogadishu-both its causes and its effects-highlighted the complexities of the post-Cold War American military mission.</p>

<p>For more information, please visit the <a href=""../clinton"">Bill Clinton home page</a>.</p><h4>Bill Clinton</h4>
