
<h2>1797-10-18 12:00 PM</h2><h1>The XYZ Affair</h1>

<p>On October 18, 1797, three Americans who were sent to France by President John Adams to represent a U.S. peace commission, were received coolly and then asked to pay a bribe in order to speak with French Foreign Minister Charles Maurice Talleyrand. This episode became known as the “XYZ Affair,” after the French agents who met with the American delegation. The incident affected U.S. relations with France and damaged the Democratic-Republican Party because of its traditional pro-French stance.</p>
<p>When France broke diplomatic ties with the United States in 1796, incoming President John Adams organized a delegation to negotiate with the French government. Charles Pinckney, John Marshall, and Elbridge Gerry arrived in Paris in October 1797 with instructions to normalize diplomatic relations and ensure French privateers would no longer harass American shipping.</p>  
<p>The American delegation encountered open hostility, and the French minister of foreign relations, Charles Maurice Talleyrand, refused to meet with them. On various occasions, four agents, later called W, X, Y, and Z by President Adams, contacted the Americans. They demanded an apology for insulting remarks made by Adams and wanted loans to the French government along with some $25,000 in bribes for French officials in return for talks with Talleyrand. Further, they implied war would result if the Americans did not meet the demands. Pinckney and Marshall refused to negotiate under such circumstances. Gerry, who sympathized with the French, urged patience. He remained in Paris until the fall of 1798, although Marshall and Pinckney left in the early months of the year.</p>
<p>When President Adams received news of the failed mission in March 1798, he called for restraint. Initially giving Congress only a partial account of events, he favored continued attempts to negotiate, but also urged Congress to strengthen the country's defenses. Many, such as Secretary of State Timothy Pickering, called for an immediate declaration of war, and war fever grew steadily throughout 1798. Federalists denounced opposition to strong government action as unpatriotic and labeled Gerry treasonous for remaining in France. After President Adams turned over to Congress all of the delegation's correspondence on the failed negotiations, Democratic-Republicans, traditionally supporters of France, found themselves on shaky ground. Unsuccessfully trying to separate patriotism from support for a particular administration, they were seen as public enemies.</p>
<p>The issues with France remained unresolved. Congress activated the tiny, new navy in 1798, and fought an undeclared naval war with France for two years. Of longer-term significance, Federalists used the anti-Democratic-Republican fervor to try to solidify their leadership. The Alien and Sedition Acts, passed in 1798 by the Federalist Congress, essentially outlawed French immigrants and criticism of the government. This step backward in Democratic-Republican's attempts to establish the idea of loyal opposition caused opposition leaders to turn to state governments as bulwarks against unrestrained federal power.</p>

<p>For more information, please visit the <a href=""../adams"">John Adams home page</a>.</p><h4>John Adams</h4>
