
<p>/images/academic/americanpresident/essayimages/10_22.jpg</p>
<h2>1962-10-22 12:00 PM</h2>
<h1>Kennedy Announces Cuban Missile Crisis</h1>

<p>On October 22, 1962, President John Kennedy announced in a nationally televised address that the United States had discovered the Soviet Union was building “offensive missile sites” on the island of Cuba. The President warned that the purpose of the Soviet missiles in Cuba could be “none other than to provide a nuclear strike capability against the Western Hemisphere” and that he would protect the United States from such a threat no matter what the cost. He explained the U.S. Navy would impose a “quarantine” or naval blockade around Cuba with the support of the Organization of American States.</p>  
<p>The Cuban Missile Crisis began on October 14, 1962, when a U-2 surveillance mission flying over Cuba photographed the construction of launch sites for medium and intermediate range ballistic missiles. These missiles, once operational, could deliver nuclear warheads to much of the United States. National Security Advisor McGeorge Bundy informed the President of the discovery the  morning of October 16. Kennedy quickly called a meeting of his top military and diplomatic advisers as well as his most trusted confidants like Theodore Sorensen and his brother, Attorney General Robert Kennedy. This group became known as the Executive Committee of the National Security Council or ExComm.</p> 
<p>Members of ExComm agreed that the Soviets must remove the missiles from Cuba, however, they disagreed about the best approach to ensure the missiles' removal. After much discussion, the President chose to use a naval blockade of Cuba to prevent further shipments of Soviet weapons from entering Cuba, but because international law considered a “blockade” an act of war, the Kennedy administration chose to use the term “quarantine” instead. Over the next few days, the world waited in anxious anticipation as Soviet ships approached the American blockade. On the morning of Wednesday, October 24, conflict appeared imminent as twenty-five Soviet ships neared the quarantine. At 10 a.m., however, the six vessels nearest the boundary all turned back.</p>  
<p>Despite the initial success of the quarantine, the crises continued without resolution. Finally, on October 26, lines of communication opened with the Soviets, but the White House received confusing messages. Meanwhile, the downing an American U-2 surveillance plane over Cuba exacerbated the crisis, placing Kennedy under increasing pressure from his military advisors to order an air strike on Cuba. The President realized he must act quickly to find a diplomatic solution.</p> 
<p>Responding to the communication from Moscow, the White House drafted a letter to Soviet Premier Nikita Khrushchev explaining that once the Soviets removed the missiles from Cuba, the United States would end its quarantine and would promise not to invade Cuba. In a secret conversation with Soviet Ambassador Anatoly Dobrynin, Robert Kennedy pledged that, in an addition to the terms in the letter, the United States would also remove American ballistic nuclear missiles from Turkey. On October 28, the Cuban Missile Crisis was resolved when the Soviets accepted the U.S. compromise. On November 20, Kennedy ended the naval blockade of Cuba after the Soviet Union had dismantled and removed the weapons from Cuba. In one of the most dramatic crises of the Cold War, Kennedy and Khrushchev avoided violent conflict.</p>


<p>To read and listen to the full text of President Kennedy's Address on the Buildup of Arms in Cuba, click <a href=""http://millercenter.org/scripps/archive/speeches/detail/3372"">here</a>.</p>

<h4>John Fitzgerald Kennedy</h4>
