
<h1>Berlin Wall Falls</h1><h2>1989-11-9 12:00 PM</h2>

<p>On November 9, 1989, East Germany fully opened its borders, including the imposing gate at the Berlin Wall. Thousands of Germans, from both East and West Germany, climbed over the wall and began to dismantle it with shovels and hammers. The jubilant scene illustrated the great changes taking place with the ending of the Cold War.</p>
<p>Since 1961, the Berlin Wall had stood as a symbolic barrier between the East and West, between communism and democracy: its fall reflected changing international relations. This episode, although memorable, was not the first or last in the relatively swift collapse of communism. Earlier in 1989, Hungary and Austria had opened their border. By spring of 1990, liberal political actors had wrested the governments of Poland, Bulgaria, Romania, Czechoslovakia, Lithuania, and Romania from the hands of communist leaders.</p>
<p>The Soviet Union itself, for decades the most powerful adversary of the United States, had been undergoing fundamental political changes throughout the 1980s, shaking its communist foundations. Soviet Premier Mikhail Gorbachev had worked to change the Soviet Union through the doctrines of <em>perestoika</em> (restructuring) and <em>glasnost</em> (opening). He had also worked with Presidents Ronald Reagan and George H. W. Bush to thaw the Cold War.</p>
<p>By December 1991, the Soviet Union had dissolved and Gorbachev had resigned; the Commonwealth of Independent States had replaced the Soviet Union. Many conservative commentators have praised Reagan and Bush for substantially contributing to the fall of communism. These observers say that the tremendous military build-up of the 1980s forced the Soviet Union to spend scanty resources to keep up, which ultimately produced the instability that spelled its end. Others claim that internal developments in the Soviet Union-such as its unsuccessful war with Afghanistan and autonomous rebellions from within-are more to blame: high U.S. spending, they claim, only sapped resources from important domestic programs and meaningful diplomatic conversation.</p>
<p>It is unlikely that this debate will soon be resolved, but the basic triumph of democracy seems inarguable. President George H. W. Bush embraced the geopolitical upheaval cautiously, and he was criticized for failing to give the moment adequate meaning and communicating its import to the American public. However, the President responded cautiously to try to avoid a backlash by hard-liners in Eastern Europe and the Soviet Union, a stance that well-informed observers applauded. 
<p>The dismantling of the Berlin Wall was a poignant illustration of the collapse of communism and the end of the Cold War. The world was then faced with restructuring the geopolitical balance that had been in place for more than forty years.</p>

<p>For more information, please visit the <a href="../bush">George Herbert Walker Bush home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
