
<p>/images/academic/americanpresident/essayimages/11_05.jpg</p>
<h2>1912-11-05 12:00 PM</h2>
<h1>Election of 1912</h1>

<p>On November 5, 1912, President William Taft was defeated by Democrat Woodrow Wilson in the presidential election of 1912. The three-way race between Taft, Wilson, and former President Theodore Roosevelt illustrated the rise of progressivism in presidential politics. Although Roosevelt's Progressive Party had one of the strongest third-party showings in American history, he and Taft divided the Republican Party vote, and Wilson easily won the election.</p>
<p>Before President Theodore Roosevelt left office in 1909, he hand-picked William Taft as his successor and worked to get him elected. But once Taft became President, Roosevelt became increasingly disenchanted with his successor. He felt Taft was not progressive enough, turning his back on environmental conservation and targeting so-called good trusts. Enraged by his protégée's tenure, Roosevelt decided to challenge him for the Republican nomination in 1912.</p>
<p>The Republicans met in Chicago in June 1912, hopelessly split between the Roosevelt progressives and the supporters of President Taft. Roosevelt came to the convention having won a series of preferential primaries that put him ahead of the President in the race for party delegates. Taft, however, controlled the convention floor, and his backers managed to exclude most of the Roosevelt delegates by not recognizing their credentials. These tactics enraged the former President, who then refused to allow himself to be nominated, paving the way for Taft to win on the first ballot.</p> 
<p>Roosevelt and his supporters bolted the Republican Party and reconvened in Chicago two weeks later to form the Progressive Party. Roosevelt became the Progressive Party candidate for President, and Governor Hiram Johnson of California joined the ticket as Roosevelt's running mate. Roosevelt electrified the convention with a dramatic speech in which he announced that he would “stand at Armageddon and battle for the Lord” and declared that he felt “as strong as a Bull Moose,” thus giving the new party its popular name.</p>
<p>At the Democratic National Convention in Baltimore at the end of June, Speaker of the House James “Champ” Clark entered as the favorite to gain the party's nomination after a strong showing in the primaries against New Jersey governor Woodrow Wilson. Democrats engaged in an intense struggle over the nomination, however, prompted by William Jennings Bryan's criticism that Clark's machine base was too close to big business. Wilson secured the nomination on the forty-sixth ballot of the convention. His selection over the more moderate, less charismatic Clark ensured the Democrats a vibrant, progressive-minded candidate to challenge the vim of Roosevelt and overshadow Taft. Democrats nominated Thomas R. Marshall of Indiana for the vice presidency.</p>
<p>Unlike many proceeding campaigns, which boiled down to contests of personality or character, the election of 1912 remained essentially a campaign of ideas. Wilson and Roosevelt emphasized their progressive ideologies on the campaign trail. Wilson devised the “New Freedom” appellation for his campaign, emphasizing a return to individualism in industrial enterprise encouraged by the end of tariff protection, the breaking up of Wall Street's control of financial markets, and vigorous antitrust prosecution. Wilson believed federal power should be used to break up all concentrations of wealth and privilege, disagreeing with Roosevelt that monopolies could serve a common good through their efficiency.</p>
<p>Roosevelt built his “New Nationalism” campaign on the back of ideas he had been advocating since his return to public life in 1910, including strengthening federal regulatory control over interstate commerce, corporate conglomeration, and labor conditions. President Taft emphasized how his brand of conservatism offered practical solutions to tangible problems facing Americans. He chided the idealism of his opponents as dangerous to the constitutional system. Socialist Eugene V. Debs joined the triumvirate with his campaign more focused on socialist education for American voters than success. Debs urged the public ownership of transportation and communication networks, progressive income and corporate taxes, and a rigorous worker protection laws.</p>
<p>With the Republican Party badly split between its conservative and progressive wings, neither Taft nor Roosevelt rightfully expected victory in November. The election yielded the Democratic Party its greatest victory since before the Civil War as it gained both houses of Congress and the presidency. The popular vote was more an endorsement of progressivism than of Wilson as he and Roosevelt combined for nearly 70 percent of the ballots cast. Wilson failed to win a majority of the popular vote, earning 41 percent of the popular vote to Roosevelt's 27 percent. Taft finished with 23 percent of the vote, and Debs made a considerable showing with 6 percent. Taft won only two states in the Electoral College: Vermont and Utah. Roosevelt carried progressive strongholds California, South Dakota, Pennsylvania, Washington, and Michigan, but could not contend with Wilson's enormous success in his home region of the South and his wins in key Northern states such as New York and Wisconsin. Wilson carried 435 of 531 votes in the Electoral College to become the nation's twenty-eighth President.</p>

<h4>William Taft</h4>
