
<h2>1888-11-06 12:00 PM</h2><h1>Cleveland Loses Re-election</h1>

<p>On November 6, 1888, President Grover Cleveland was defeated in his bid for re-election by the Republican candidate, Benjamin Harrison. Although President Cleveland won the popular vote, Harrison won the Electoral College and thus the presidency.</p> 
<p>The Republicans entered the election of 1888 with a well-organized and effective campaign structure. Their candidate, Benjamin Harrison, was the grandson of President William Henry Harrison. He was a former Civil War general and Indiana senator who ran an energetic campaign and exhausted himself delivering more than eighty speeches in sixteen weeks. The Democratic campaign was far less organized, and President Cleveland put forth little effort. Much of the public speaking in the Democratic campaign was left to the nominee for vice president, Allen G. Thurman, who was in poor health.</p>
<p>The central issue in the 1888 campaign was the tariff. Benjamin Harrison advocated the Republican position in support of a high protectionist tariff, while Cleveland pushed for tariff reform. Poor campaigning dashed Cleveland's hopes of educating the public on the importance of tariff reform. Another significant issue was the treatment of Civil War veterans. Harrison argued for better treatment of veterans by the government and criticized Cleveland's veto of Civil War pension legislation.</p>
<p>Two of the major events in the election took place towards the end of the campaign. Buying votes was a relatively common practice in Indiana, and the treasurer of the Republican National Committee, W. W. Dudley, was accused of writing a letter to Republican field workers encouraging them to drive up the prices of votes to exhaust Democratic funds. A mail clerk found the letter and had it published, although the damage this did to Harrison's campaign is debatable. The second event was the publishing of the "Murchison Letter." Republican George Osgoodby wrote a letter, under the name Charles F. Murchison, to the British ambassador, Lord Lionel Sackville-West. In it, Murchison claimed to be a former British citizen who came to the United States and wanted advice on the 1888 election. The minister responded by endorsing Grover Cleveland; at a time when Anglophobia was on the rise, the news that Britain considered Cleveland a friend may have cost him a number of votes in the crucial state of New York, although the effect of the letter on the election is not certain.</p>
<p>In the end, Cleveland won the popular vote by a margin of more than 4,000 votes, but Harrison won the Electoral College vote 233 to 168, and thus the presidency. The next presidential election in 1892 was a rematch, and Cleveland defeated Harrison and reclaimed the presidency. He thus became the only President to serve nonconsecutive terms, winning the office once again after losing as the incumbent.</p>

<p>For more information, please visit the <a href="../cleveland">Grover Cleveland home page</a>.</p><h4>Grover Cleveland</h4>
