
<p>/images/academic/americanpresident/essayimages/11_19.jpg</p>
<h2>1794-11-19 12:00 PM</h2>
<h1>Jay Treaty Signed</h1>

<p>On November 19, 1794, American statesman John Jay signed the Amity, Commerce, and Navigation Treaty with Britain. The treaty, now known as Jay's Treaty, was designed to resolve  issues between the United States and Britain. Although the treaty left some important issues unresolved and its ratification divided politicians in the young federal government, it successfully allowed the United States to avoid war with its more powerful adversary, Britain. </p>
<p>In the 1790s, the United States was struggling to assert both its political and economic independence, and the new nation encountered difficulties in foreign relations when its two primary trading partners, Britain and France, went to war yet again. President George Washington sought to follow a policy of strict neutrality, allowing American merchants and ships to trade with both countries while aiding neither in their war efforts. Britain, however, confiscated many American ships and their cargoes, arguing that they aided the French war effort. British naval vessels also frequently impressed American sailors, forcing them to work on British ships. Britain, in addition, still barred American ships from participating in the lucrative West Indian trade, a policy it formulated during the American Revolution. The United States was also upset by Britain's refusal to evacuate its forts in the Great Lakes area, although it had agreed to do so in the Treaty of Paris of 1783.</p>
<p>These British actions outraged many Americans. Attempting to keep the United States out of war, President Washington worked for a diplomatic solution. He sent John Jay, Chief Justice of the Supreme Court, to England in 1794 to negotiate a peaceful resolution of the issues. Jay concluded a treaty in which Britain promised to leave its forts in the Great Lakes region, agreed to arbitration for disputes over the Canadian border (one of the first instances of arbitration in diplomatic history), and gave American ships limited trading rights with British possessions in the East and West Indies. The treaty left unresolved, however, the issues of impressments and American neutrality.</p>
<p>Jay's Treaty still needed to earn Senate ratification - and a tough battle loomed. The ratification process, in which Federalists supported and Democrat-Republicans opposed the treaty, became bogged down in partisan differences, destroying what little remained of the consensus President Washington had tried to instill in the federal government. As a piece of diplomacy, Jay's Treaty was imperfect but still a success. The treaty did not secure everything the Americans wanted because it failed to deal with the impressment problem and American neutrality, and because it seemed to acquiesce to British supremacy on the seas. The treaty, however, did put off direct conflict between America and its much stronger rival, and it won the United States important territorial and trade concessions - no small feat for a new nation confronting a global power.</p>

<h4>George Washington</h4>
