
<h2>1963-11-22 12:00 PM</h2><h1>Kennedy Assassinated</h1>

<p>On November 22, 1963, President John Kennedy was shot and killed while traveling in a motorcade in Dallas, Texas.</p>  
<p>The President and First Lady had gone to Texas in an attempt to bolster Democratic support for his presidency in the South. While the President and First Lady were riding in a motorcade with Texas governor John Connally and his wife, the open limousine turned into Dealey Plaza and gunshots rang out. Kennedy, shot in the neck and the head, was rushed to Parkland Memorial Hospital. A short time later, President John F. Kennedy was pronounced dead. With a blood-stained Jacquelyn Kennedy at his side, Vice President Lyndon Johnson was sworn in as President of the United States.</p> 
<p>The search for Kennedy's assassin began immediately. The police arrested Lee Harvey Oswald in a nearby movie theater. Witnesses had identified shots coming from the sixth floor of the Texas School Book Depository where Oswald worked. Oswald, however, was never tried for the crime. Two days later, Jack Ruby, a Dallas businessman and nightclub owner, shot Oswald dead in the basement of the Dallas police station as he was being transfered to a jail. This strange turn of events quickly cast doubt about who had perpetrated the assassination. President Johnson appointed Chief Justice Earl Warren to head a commission to investigate the incident. In less than a year, the Warren Commission concluded that Oswald, working alone, was guilty of the act. Many Americans remain unsatisfied with this simple explanation for such a horrific event.</p>
<p>Kennedy's death proved to be a political asset for the legislatively astute Johnson. "Let us continue," Johnson told Congress and the American people echoing Kennedy's inaugural address. Framing his programs as a way of fulfilling Kennedy's legacy, Johnson passed the most significant civil rights legislation in American history. Still, for a whole generation of Americans, Kennedy's death would symbolize an end of a time of innocence and the beginning of a turbulent period in American history.</p>

<p>For more information, please visit the <a href="../kennedy">John Fitzgerald Kennedy home page</a>.</p><h4>John Fitzgerald Kennedy</h4>
