
<h2>1921-11-23 12:00 PM</h2><h1>Harding Signs Sheppard-Towner Act</h1>

<p>On November 23, 1921, President Warren Harding signed the Sheppard-Towner Maternity and Infancy Protection Act, which contributed matching federal funds to states to establish and run prenatal and child health care centers. Although it was not a strong act, it was still a significant move by the federal government toward providing public health care to mothers and infants.</p> 
<p>Reformers had sought similar legislation since 1917, but it was not until 1921 that a number of factors combined to push it through. In 1912, President William Taft established the Children's Bureau, which began a nationwide investigation of maternal and infant mortality rates. The agency soon discovered that nearly 80 percent of U.S. women did not receive proper prenatal care-a fact starkly illustrated during World War I when thousands of men failed to pass their physicals due to afflictions stemming from inadequate medical care as children. Indeed, while the Bureau found a correlation between economic level and mortality rates, the mortality rates at all income levels were much higher in the United States than in other industrialized nations.</p>
<p>While the Bureau's findings clearly demonstrated the existence of a severe problem, there was little agreement on how to solve it. The few existing state-run child welfare clinics had proven effective at reducing infant mortality and bettering overall health, and many groups sought to duplicate this model on a national scale. Others, most notably the American Medical Association (AMA), were hesitant to accept a widening of federal involvement in medical care. The AMA was wary of government encroachment on their autonomy as medical professionals and criticized the act as neo-socialist. These reservations succeeded in blocking the passage of such legislation as early as 1918.</p>  
<p>With the enactment of the Nineteenth Amendment in 1920 granting women the right to vote, however, political power shifted dramatically. Women had long been the leading voices of reform in various areas of social welfare, especially in regards to child and maternal health care. President Harding responded to this newly created constituency by actively supporting the passage of Sheppard-Towner as well as appointing women to high posts within his administration. The legislation itself proved to be temporary, however. Underfinanced from the beginning, the AMA-led campaign against Sheppard-Towner finally succeeded in 1929 when Congress did not renew its funding.</p>

<p>For more information, please visit the <a href=""../harding"">Warren Gamaliel Harding home page</a>.</p><h4>Warren Gamaliel Harding</h4>
