
<h3>U.S. Capital Moves to Philadelphia</h3><h2>1790-12-6 12:00 PM</h2>

<p>On December 6, 1790, the United States Capital officially moved from New York City to Philadelphia, Pennsylvania. The capital remained in Philadelphia until 1800 when it permanently settled in Washington, D.C.</p> 
<p>The United States government spent its first year (1789-1790) under the Constitution in the city of New York. During much of the preceding confederation period (1776-1787), however, Congress had resided in Philadelphia. Upon the formation of a new national government under the Constitution, the city campaigned vigorously for the federal government to return. While Congress chose to establish the nation's capital along the Potomac River in the District of Columbia, it also rewarded Philadelphia; it chose the Pennsylvania city to house the federal government until 1800 while its offices in Washington were under construction.</p>
<p>Arriving in time for the December 1790 session, Congress moved into Philadelphia's county courthouse, Congress Hall. These quarters quickly proved too small, and in 1793 the building had to be enlarged. The Supreme Court met in the mayor's courtroom in Philadelphia's city hall, and President George Washington moved into the former home of a local politician. As part of its improvement program, Pennsylvania offered to build Washington a presidential mansion. Washington, however, feared the city would use the residence in a bid to keep the capital in Philadelphia permanently. He also worried that living in grandeur would send the wrong message to Americans and the world about the nature of the new American republic. When Pennsylvania built the mansion anyway, Washington refused to live in it.</p>
<p>The initial adjustment period proved somewhat chaotic as legislators searched for housing in a city rapidly filling with tailors, barbers, shoemakers, and other entrepreneurs who hoped to capitalize on the presence of the federal government. Prices rose accordingly with the increased demand for goods and services, and many congressmen bemoaned the higher cost of living. The profusion of balls, dinners, dances, public lectures, musical performances, and theater spurred by the federal presence created a rich cultural environment. President Washington's weekly reception for politicians and foreign diplomats and Martha Washington's Friday evening soir&eacute;es commanded the highest priority in the city's social scene. Washington's careful cultivation of public esteem and deference in Philadelphia enhanced his image as a national symbol and fostered the growth of American nationalism. In an era when most Americans looked to Congress as the primary branch of government, Washington's public persona in Philadelphia helped to elevate the stature of the presidency and solidify its importance in the American political system.</p>

<p>For more information, please visit the <a href="../washington">George Washington home page</a> or go to more <a href="index">Events in Presidential History.</a></p>
