
<p>/images/academic/americanpresident/essayimages/12_08.jpg</p>
<h2>1993-12-08 12:00 PM</h2>
<h1>Clinton Signs NAFTA</h1>

<p>On December 8, 1993, President Bill Clinton signed the North American Free Trade Agreement (NAFTA), which eliminated nearly every trade barrier between the United States, Canada, and Mexico, creating the world's largest free trade zone. The House of Representatives approved NAFTA on November 17, 1993, by a vote of 234 to 200. Remarkably the agreement's supporters included 132 Republicans and only 102 Democrats. That unusual combination reflected the challenges President Clinton faced in convincing Congress that the controversial piece of legislation would truly benefit all Americans.</p>   
<p>President George H.W. Bush was NAFTA's original sponsor, signing the deal on December 17, 1992. The trade agreement ended tariffs between Mexico, America, and the United States, and set a 15-year timetable for the elimination of most other impediments to international investment and commerce between the three nations. Like many Republicans, President Bush believed that open economic borders between nations would benefit all concerned. Ideally, as production rose to meet the new demand for American exports, jobs, wages, and the economy as a whole would improve. However, securing Congressional approval fell to the newly elected President Bill Clinton. It was not an easy task.</p>
<p>Labor leaders were skeptical of NAFTA's promises. They believed that American corporations would flee the United States in order to profit from much lower Mexican labor costs and the new absence of tariffs. Presidential candidate Ross Perot spoke to those concerns when he famously predicted a giant “sucking sound” as U.S. jobs were lost to America's southern neighbor. The fears of labor&mdash;traditionally one of the strongest components of the Democratic coalition&mdash;helped explain why passage of NAFTA proved so difficult.</p>
<p>President Clinton and key members of his administration worked tirelessly to assuage the fears of key House Democrats. The President inserted limits on agricultural imports to minimize the negative effects of competition on produce. He also created a North American Development Bank in order to assist development along the Mexican border and show sympathy with the concerns of Hispanic Representatives. Clinton was willing to risk alienating American labor to some degree because he was convinced that long-term prosperity depended on free trade between nations, and because he felt that his administration needed an important, visible early win to generate momentum and credibility. NAFTA amounted to an administration victory, but many still regarded it as a net loss for American labor and the environment, which they claimed suffered in the absence of adequate Mexican regulations.</p>

<h4>Bill Clinton</h4>
