
<p>/images/academic/americanpresident/essayimages/12_19.jpg</p>
<h2>1998-12-19 12:00 PM</h2>
<h1>House Impeaches Clinton</h1>

<p>On December 19, 1998, the House of Representatives voted to impeach President Bill Clinton on charges of perjury and obstruction of justice.</p> 
<p>The House of Representatives, which is responsible for instigating impeachment proceedings, originally considered four articles of impeachment, but declined to charge the President with one count of perjury and abuse of power. That impeachment proceeded on two grounds rather than four did not testify to a bastion of GOP support in the House, for Republican Representatives had staunchly refused a Democratic plea simply to censure the President for reprehensible behavior. Clinton had wait through two agonizing months as the Senate received the case from the House, took testimony, and debated whether or not he could continue as President.</p> 
<p>The nation, too, was engaged in a furious debate over impeachment. Republicans and their conservative supporters felt that they were taking a stand for morality and integrity. The President's predicament flowed from an affair with the former White House intern, Monica Lewinsky, and his efforts to conceal the moral lapse from lawyers in the Paula Jones case, the public, and apparently even his family. The presidency was not only a position of legal and military leadership, Clinton's adversaries argued, it was a uniquely visible symbol of America, and as such carried weighty responsibilities of moral leadership. Democrats and their liberal supporters argued that impeachment was intended to remove Presidents who clearly abused their power as Presidents, for misdeeds like treason or using office to harm opponents. They alleged that Republicans were bent on a destructive and hypocritical “sexual McCarthyism,” policing what people did in private intimate relations, although some prominent Republican and conservative leaders had themselves committed affairs.</p> 
<p>The Senate acquitted President Clinton on February 12, 1999. Afterwards, Clinton apologized to the nation for the ordeal and hoped that the country could return to the business at hand. Answering a reporter, who asked whether Clinton could in his heart forgive and forget the actions of those who had tried to remove him from office, the President offered a conciliatory response: “I believe any person who asks for forgiveness has to be prepared to give it.”</p>

<h4>Bill Clinton</h4>
