
<h2>1860-12-20 12:00 PM</h2><h1>South Carolina Secedes</h1>

<p>On December 20, 1860, a secession convention called by the South Carolina legislature voted unanimously, 169-0, to secede from the United States. After the election of Abraham Lincoln on November 6, 1860, South Carolinians perceived a threat to their slave system that Congressional compromise could not pacify. One South Carolina writer observed, “the Secessionist Party of 1860 is literally and emphatically the State itself.”</p>
<p>The secession movement in South Carolina was explosive. Leaders mobilized citizens and held torch light processions. Fiery speeches by prominent Carolinians complemented the fireworks and rockets that were set off. While many Unionists in the upper South attempted compromise, South Carolina politicians fanned the flames of “popular excitement” over secession. On November 10, South Carolina senator James Chesnut resigned, followed by Senator James H. Hammond. Governor William H. Gist called for ten thousand volunteers to form a militia. Some South Carolinians were hesitant that the Palmetto State was acting too swiftly and might be isolated. It soon became clear that six other Southern states, including Mississippi, Florida, Alabama, Georgia, Louisiana, and Texas, would each hold secession conventions. Few who supported secession in South Carolina hesitated to act. Francis W. Pickens, who became South Carolina's new governor in December, announced the state's secession on December 24.</p>
<p>In his annual message to Congress, President James Buchanan repudiated any state's right to secede but blamed the South Carolina secession movement on the “long-continued and intemperate interference of the Northern people with the question of slavery.” Buchanan tried diplomacy to keep South Carolina from seceding. The two sides could not reach an agreement. On December 26, Buchanan ordered Major Robert Anderson to move from Fort Moultrie to the more isolated Fort Sumter in Charleston harbor. South Carolina forces moved into Moultrie and other federal installations. On January 5, 1861, Carolinians fired on a ship sent to re-supply Fort Sumter, but Buchanan refused to respond with force. Buchanan deferred to Congress, which refused to authorize military action. The President gratefully acquiesced. Unless attacked or starved, he would leave the Fort Sumter situation to President-elect Abraham Lincoln.</p>
<p>Many Southerners in Buchanan's cabinet resigned, and his administration was thrown into disarray. Hasty cabinet replacements were no help, and the administration fell apart.  Buchanan's indecisiveness and willingness to compromise with the secessionists appalled Northerners, and South Carolina's example encouraged more states to rise. When Buchanan took office, there were thirty-two states in the Union; when he left there were only twenty-five.</p>

<p>For more information, please visit the <a href=""../buchanan"">James Buchanan home page</a>.</p><h4>James Buchanan</h4>
