
<h2>1913-12-23 12:00 PM</h2><h1>Federal Reserve Act Signed</h1>

<p>On December 23, 1913, President Woodrow Wilson signed the Federal Reserve Act into law. The act created a Federal Reserve System, comprised of a Federal Reserve Board, twelve regional reserve banks, and the underpinnings of a smooth central banking system. It was the most comprehensive overhaul of the nation's banking system since the Civil War and represented one of the crowning achievements of President Wilson's New Freedom program. It helped to safeguard America's financial institutions, the American economy, and the supply of U.S. currency, and it created a new system that allowed a level of governmental control of the monetary supply that was unprecedented in American history. The Federal Reserve Act still provides the framework for regulating the nation's banks, credit, and money supply even today.</p>
<p>Wilson began to craft his monetary system soon after his election in 1912. He met with House Banking Committee Chairman E.C. Glass in December to discuss a variety of banking system plans emerging in Congress. Glass, a conservative Democrat from Virginia, favored a decentralized private system. Wilson remained wary of such a proposal and convinced Glass to consider drafting a plan that included privately controlled regional reserve banks that answered to a central government board with a minority representation for private bankers. Glass's plan contrasted with a competing Senate bill, drafted by progressive Oklahoma senator Robert Owen, which erected a system of reserve banks under direct governmental control. Progressives rallied to Owen's proposal and recoiled from Glass's privatization scheme as a system that would leave Americans at the mercy of Wall Street. </p>
<p>Wilson conferred with Secretary of the Treasury William McAdoo and adviser Louis Brandeis on the proposals making their way through Congress. In a meeting on June 11, 1913, Brandeis pushed the President to support governmental control of the banking and currency systpem of the nation as progressives had proposed. He also convinced the President to leave private bankers off the proposed Federal Reserve Board. After his meeting with Brandeis, Wilson urged Glass to revise his bill. The President addressed Congress on June 22 to push forward banking reform, which he claimed must remain a government responsibility. After a bruising six-month debate in Congress, the progressives' version of the Federal Reserve Act passed Congress on December 19, and Wilson signed it December 23, 1913.</p>
<p>The Federal Reserve Act established a system of twelve districts that each housed a Reserve bank. It also required national banks to join the federal system and contribute six percent of their capital to the system. State banks and trust companies could also join the system. Federal Reserve banks issued notes to member banks with the amount of currency issued regulated by a central Federal Reserve Board in Washington, DC. This board was comprised of the secretary of the treasury, the comptroller of currency, and six other presidential appointees. The act allowed a more flexible system of currency distribution that could respond to economic conditions unique to a given region or that impacted the entire nation. The flexibility of the system benefited both farm and business interests. </p>

<p>For more information, please visit the <a href="../wilson">Woodrow Wilson home page</a>.</p><h4>Woodrow Wilson</h4>

